### ISSUE TITLE
Misnamed fields and broken links on http://docs.smarthealthit.org/profiles/

### ISSUE THREAD

**Issue by climoli** [smart-on-fhir/smart-on-fhir.github.io#107]
We went through the FHIR resources associated with the SMART profiles and found some discrepancies that we wanted to make you aware of (see attached). Please let us know if the assumptions we've made about the field and resource name updates are correct (rows 2-10). Please also let us know what we should do about the fields SMART specifies should be present but are not in the FHIR resource (rows 11-15).

Thank you,
Craig
[SMART Profile Documentation - Problem Fields.xlsx](https://github.com/smart-on-fhir/smart-on-fhir.github.io/files/75147/SMART.Profile.Documentation.-.Problem.Fields.xlsx)

**Comment by jmandel** [comment]
Thanks for these! We've already had a [fix submitted](https://github.com/smart-on-fhir/smart-on-fhir.github.io/pull/106) for `Observation.reliability`. The others we'll need to fix! (If you're willing/interested, please feel empowered to submit a Pull Request with these fixes.)

**Comment by grahamegrieve** [comment]
"No known allergies": Encoded as List. You should update that now that you can negate in AllergyIntolerance directly

typo : FamilyHitory

systolic/diastolic pairing should be done by component observations now

**Comment by jmandel** [comment]
Thanks for these comments: finally closing the loop!

Re:
Height measurement in FamilyMemberHistory: this is an extension, not a core element. But it should be valid.

Re: negated allergies: I still have some concerns with this representation; don't know how much we can say at the moment.
