### ISSUE TITLE
Unable to connect to grahame's server with demo Jquery app

### ISSUE THREAD

**Issue by Healthedata1** [smart-on-fhir/smart-on-fhir.github.io#108]
I've been modifying this demo on JSfiddle to use as a demo on NutritionOrder at HIMSS.  I noticed I can't point to any endpoint like Grahame's open server.  I'm not pretending I know what is happening under the hood with the authorization and certificates, but HAPI works if I change the endpoint from 'http' to 'https' and the browser complains about the certificate, but Grahame's server just claims the patient is not found. ( its there I can access it from the browser  eg/  Patient/111).   Any explanation or solution would be great.

Thanks, 

Eric

**Comment by jmandel** [comment]
Thanks for the report, Eric - can you save and share a link to the jsfiddle that you have created, so we can see what's going on?

**Comment by Healthedata1** [comment]
here is the link: https://jsfiddle.net/ehaas/6L6qv63t/2/

Last I checked
valid patient resource id for HAPI = 1
valid patient resource id for grahames server = 111
valid patient resource id for Furore = f009


Thanks,

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by Healthedata1** [comment]
oops this fiddle https://jsfiddle.net/ehaas/mq07txsp/7/ uses
FHIR.client(demo);   the other one I sent uses a get -though they behave
the same.

Eric


Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by nschwertner** [comment]
The problem seems to be CORS related. JSFiddle is running on HTTPS, but Grahame's server is on HTTP, so the AJAX request fails with `Blocked loading mixed active content "http://fhir2.healthintersections.com.au/open/Patient/111"` (see http://www.w3.org/TR/access-control/#user-agent-security). Unfortunately, it does not seem like Grahame's server responds to HTTPS requests. Perhaps try running your fiddle code locally on HTTP?

**Comment by Healthedata1** [comment]
Thanks, I will ask GG as well if there is way he can open up to https
requests too.


Eric.

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>
