### ISSUE TITLE
FHIR call details in the server quick start

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/smart-on-fhir.github.io#11]
In the [server quick start](http://docs.smartplatforms.org/tutorials/server-quick-start/):

- The app asks also for the `FamilyHistory` of the patient, not just for the weight/height/BMI observations

- In the observation response example the quantities have a units `code` without the corresponding `system`, that is compulsory if `code` is specified

**Comment by nschwertner** [comment]
Thank you for pointing this problem out. Probably this example was copied incorrectly some time ago. From what I see, our sample patient generator includes the system in the units of measurement:
https://github.com/smart-on-fhir/sample-patients/blob/master/bin/fhir_templates/observation.xml#L31

We will fix the docs.

**Comment by nschwertner** [comment]
Docs at http://docs.smartplatforms.org/tutorials/server-quick-start/ are up to date
