### ISSUE TITLE
Standalone Launch of growth-chart app

### ISSUE THREAD

**Issue by hussain-Icoegroup** [smart-on-fhir/smart-on-fhir.github.io#112]
Can the **growth-chart** app(or others) be launched standalone without the request having to generate from an EHR? 
-If it's possible then what customizations are needed to be done in the **launch.html** file?
-Or is the standalone launch meant for mobile apps only?

Thanks

**Comment by jmandel** [comment]
The app expects single-patient context. So you could easily create a
"standalone-launch.html" that the "launch/patient" scope to the requested
list. Then you should be able to call it with just an "iss" parameter and
no "launch".

**Comment by hussain-Icoegroup** [comment]
Thanks
One more thing, so that means the Authorization server(for eg, mitreid-openid-connect) needs to be customized such that it accepts requests without a **launch **query param? 
What I mean to say is that launch should be made optional inside the auth-server and auth-server needs not make a call back to the ehr. Is it?

**Comment by jmandel** [comment]
The assumption here is that your EHR's authorization server supports
SMART's "Standalone Launch" protocol (e.g. our sandbox server does this).
