### ISSUE TITLE
Example of Standalone launch sequence

### ISSUE THREAD

**Issue by vijaykumarxps1** [smart-on-fhir/smart-on-fhir.github.io#119]
Hello sir,
 their is any example of Standalone launch sequence application in javascript.

**Comment by nschwertner** [comment]
Are looking for an example or would like to share an example with us?

**Comment by nschwertner** [comment]
Just added a standalone app example in https://github.com/smart-on-fhir/sample-apps/tree/master/standalone The only difference between this app and the simple-app is the presence of the `launch/patient` scope. You can launch the app with something like http://localhost:8000/fhir-app/launch.html?iss=https%3A%2F%2Ffhir-api-dstu2.smarthealthit.org
