### ISSUE TITLE
Writing resources to FHIR servers

### ISSUE THREAD

**Issue by Gyannea** [smart-on-fhir/smart-on-fhir.github.io#121]
A very important use case that I have not seen much about is the ability to write resources to the server; in particular for remote patient monitoring. Security (authorization, authentication, and data security) is critical in such an exchange. The Personal Connected Health Alliance (PCHA) has developed such standards for the delivery of device measurement data to the health care provider. These standards are used in the IHE Remote Patient Monitoring Profile. So far that exchange is based upon HL7 V2 messaging and the exchange of CCDA documents.

The PCHA use case with a standardized means to handle security is also needed for patient-administrated device data expressed as a FHIR Bundle. How would PCHA be able to get involved in the development of this process?

Thanks,  Brian Reinhold

**Comment by jmandel** [comment]
Today the SMART API does define sport for writing resources as well as
reading them. You can try this in our sandbox. But it's important to note
that real-world EHR vendors are focusing on read access (because, among
other reasons, that's a regulatory requirement). Today for example, I think
Cerner supports writing free text notes, and need Problem -- but not yet
discrete device observations.

I think the best way to get involved will be to first try integrating a
sample application into our that box, and share your experience in that
process.
On May 13, 2016 6:40 AM, "Gyannea" <notifications@github.com> wrote:

A very important use case that I have not seen much about is the ability to
write resources to the server; in particular for remote patient monitoring.
Security (authorization, authentication, and data security) is critical in
such an exchange. The Personal Connected Health Alliance (PCHA) has
developed such standards for the delivery of device measurement data to the
health care provider. These standards are used in the IHE Remote Patient
Monitoring Profile. So far that exchange is based upon HL7 V2 messaging and
the exchange of CCDA documents.

The PCHA use case with a standardized means to handle security is also
needed for patient-administrated device data expressed as a FHIR Bundle.
How would PCHA be able to get involved in the development of this process?

Thanks, Brian Reinhold

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/121>

**Comment by Gyannea** [comment]
Josh,

Thanks for the reply. First the primary effort of PCHA is to specify a standardized means of transferring remote patient measurements to health care providers in a standardized format (V2 messages and V3 documents and now FHIR resources) which can then be read by other tools. Since the data is coming from outside the enterprise and typically originates in a patient’s home, security and authentication is an important component.  (Actually the greatest part of this challenge is standardizing the device-to-collector interface but I won’t bother you with those trials and tribulations!)

PCHA (Continua/IHE) is interested in supporting the FHIR data model in its end-to-end transfer of patient measurement data. At the moment we have used a set of FHIR resources wrapped in a transaction bundle to transfer patient measurements to a FHIR-based EHR. PCHA already supports such secured and authenticated transfers to V2 and V3 EHRs. When Web services are used SAML/TLS is used for authentication/encryption and when RESTFul ‘services’ are used oAuth/TLS is used for authentication/encryption. The RESTFul model works equally well with the FHIR bundle replacing the V2 message but we would like to harmonize with SMART on FHIR if they are going to define a security/authorization model. PCHA has specified that oAuth is required but how one obtains that oAuth token is open.

From what I can understand a very specific oAuth model is being specified and if that is the case it would be a good point of harmonization.

There also seems little support for Java and/or Android; both which are open. That seems surprising.

Brian

**Comment by jmandel** [comment]
That's correct: our OAuth profile attempts to lock down the authorization
details for interoperability between app (e.g. the software that would be
supplying device data in your use case) and EHR. Details at
http://docs.smarthealthit.org/authorization

There is Java client based on HAPI at
https://healthservices.atlassian.net/wiki/plugins/servlet/mobile?contentId=24543236#content/view/24543236

**Comment by Gyannea** [comment]
Josh,

I have looked at this page and am currently looking at the standalone application case and trying to get an idea of how much is out of band and a business decision, and how much is specified by the standard.

As I understand it the oAuth token request is using the client credentials (1.3.4) in the oAuth standard.
The standard does not specify how one obtains the credential. The common approach is username-password and public/private key.

In any case, I am looking at the flow diagram for the standalone app ‘launch’ sequence. To be honest with you, the use of the word ‘launch’ I find confusing. I am not sure what is ‘launching’;  in the PCHA use case the standalone application’s primary job is to collect measurement data from patient devices and is ‘launched’ by the user (or maybe always running on some set top box). When the data is retrieved, the measurements are sent to one or more different service endpoints as a V2 message or FHIR bundle using the appropriate transports. These destination endpoints maybe dynamically changed.

To maximize flexibility and minimize user configuration agony the HL7 hData standard is used to get the capabilities and destination addresses of the endpoint server. This step seems equivalent to the
GET https:// (fhir base url)/metdata line in the standalone ‘launch’ diagram. In hdata the ‘metadata’ is replaced by ‘root’. The client gets a root.xml with the endpoint capabilities and destination addresses as specified in the HL7 Hdata standard. All the user needs is the base url.

In the example does this metadata data indicate the type of oAuth request supported?

At the connectathon I was able to upload the bundle (unsecure) successfully to several FHIR servers. If I were to work with a few of the implementers of these servers to establish a SMART on FHIR-like authorization/security framework for the bundle upload, how would we proceed? (Clearly the scope will not be those of the current SMART on FHIR use cases but it will be for uploading).

Thanks for your help!

Brian

**Comment by jmandel** [comment]
Hi Gyannea,

SMART on FHIR uses "client credentials basic authorization header" to
authenticate a client to the authorization endpoint. Note that a client
alone cannot obtain an access token without the prior approval of a user.
That is, we use OAuth's "authorization code flow", so a client obtains a
code and then exchanges that code (along with its credentials) to request
an access token.

You must register your client with a specific server; for example, you can
register with SMART's sandbox at
http://docs.smarthealthit.org/sandbox/register/ .

Then you'll want to ask for a scope like "user/*.write" if you want to be
able to create new data in our sandbox.

We are using HL7 FHIR and not "hData" per se; I'm not sure what you're
describing on that front.

**Comment by Gyannea** [comment]
Josh,

Yes it is understood that there must be some pre-arranged out-of-band exchange with the server.

The ‘HL7 hData’ part is only for capability exchange. After that there is just a RESTFul FHIR. That capability exchange must be semantically equivalent to that ‘metadata’ GET in the flow diagram, though I have no idea what one GETs when one makes that request. The hData root.xml has a standardized means of indicating what the server supports and what the destination addresses are for whatever it is one is doing. One of those capabilities could be the destination address of the oAuth server.

Okay I am looking at the registration form. The application is a standalone Android application. The user starts it by tapping an ICON. The application starts scanning for BT and BTLE devices.

I have no idea what to enter for the following three fields:

‘Launch URI’
‘Redirect URI’
‘Logo URI’

Thanks,

Brian
