### ISSUE TITLE
Document the format of the `launch` URL parameter

### ISSUE THREAD

**Issue by tiziano88** [smart-on-fhir/smart-on-fhir.github.io#128]
Currently the http://docs.smarthealthit.org/authorization/scopes-and-launch-context/ page does not really explain how the `launch` URL parameter is meant to be used; in fact, one of the examples mentions `launch=abc123`, but looking at how the actual applications populate that parameter, it seems to me it is actually a JWT token with details about the launch context (e.g. patient etc.). Should this be clarified in that page?

**Comment by jmandel** [comment]
Th `launch` URL parameter is used in our EHR Launch flow, when the EHR opens up a window onto the app and includes a `&launch=` parameter.  The "launch" URL parameter is opaque to the app, which means means that the app doesn't need to know anything (and shouldn't assume anything) about the format of this parameters. Some EHRs may use a JWT (JWS or JWE); others may use a random number. It doesn't matter to the app.

Does this help clarify?

I'm going to close this issue, but please feel free to follow up with suggested language if you can think of a way to make this more clear in our docs.

**Comment by tiziano88** [comment]
Thanks @jmandel , appreciate your quick reply and clarification. So I am writing from the point of view of a EHR that handles OAuth2 authentication; given what you said, it seems that even in stand-alone mode, the app will link back to the EHR to show e.g. the list of patients, and then from there launch the app again, this time passing the launch context (which will be available during the authentication and authorization steps). Does this sound right?

**Comment by jmandel** [comment]
In a standalone launch, app developers have two choices:

1. The app can ask for user-level permissions (like `user/*.read`) and then, once it's been approved, the app can query for whatever data it needs. This works great for apps that need data on >1 patient at a time (e.g. a schedule management app), but it can also be used to build an in-app patient selection tool (not recommended, but sometimes practical).

2. If an app really just wants to run on one patient at a time, app can do a standalone launch and ask for a scope of `launch/patient`. When this happens, then it's the EHR's job to display a patient selection screen as part of the OAuth approval
