### ISSUE TITLE
Modified Sequence Diagram

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#13]
![new_confidentialv2](https://cloud.githubusercontent.com/assets/10760477/6454408/0d6a1f78-c0fe-11e4-8d4e-feb166f88535.png)

URL to editable diagram is at https://www.websequencediagrams.com/?open=78051

**Comment by jmandel** [comment]
Thanks Dixie! The one tweak I'd suggest (or question I'd ask) is that when an app launches from the EHR, it's launching from a UI system (the thing clinicians actually call "the EHR" -- e.g. PowerChart for Cerner, or Hyperspace for Epic) and not specifically from the authorization server. I'm hesitant to add a whole new actor just for that point... but maybe we should just remove the first arrow and just say the starting state is "EHR user has launched the app"...

BTW, it would help if you could include the websequencediagrams.com "edit link" URL for this example, so we can iterate on it more easily.

**Comment by bakerdb** [comment]
I agree with you!  In fact, my initial diagram opmitted the "Redirect to app" line (as you suggest here), but I decided to put it in dashed just for consistency with the current diagram.  I agree that it's better to leave it out.  I'll make that change and resubmit, along with the websequencediagrams.com<http://websequencediagrams.com> URL.

Thanks for checking this out so quickly.

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 2, 2015, at 3:40 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Dixie! The one tweak I'd suggest (or question I'd ask) is that when an app launches from the EHR, it's launching from a UI system (the thing clinicians actually call "the EHR" -- e.g. PowerChart for Cerner, or Hyperspace for Epic) and not specifically from the authorization server. I'm hesitant to add a whole new actor just for that point... but maybe we should just remove the first arrow and just say the starting state is "EHR user has launched the app"...

BTW, it would help if you could include the websequencediagrams.com<http://websequencediagrams.com> "edit link" URL for this example, so we can iterate on it more easily.

**Comment by bakerdb** [comment]
![new_confidentialv2](https://cloud.githubusercontent.com/assets/10760477/6454452/7d8437da-c0fe-11e4-910d-2ba42b720171.png)

**Comment by bakerdb** [comment]
I think the link to this modified page is http://www.websequencediagrams.com/?lz=bm90ZSBsZWZ0IG9mIEVIUl9BUzogRUhSIFVzZXIgaGFzIGxhdW5jaGVkIHRoZSBhcHAKAC4FcmlnaAAvBUFwcDogUmVxdWVzdCBhdXRob3JpemF0aW9uCkFwcC0-PgBNCCBSZWRpcmVjdCB0bwBhCSBBACsHZQBIDwCBAwhBdXRoZW50aWNhdGUgYW5kAFoJZSBBAHYWIE9uIGFwcHJvdmFsCgCBTAYtPj4AFQYAdwxhcHA6cgCBDAdfdXJsP2NvZGU9MTIzJi4uLgCBNgYAgTIJUE9TVCAvdG9rZW4AHgkAgRoXQ3JlYXRlIAAnBTpcbntcbmFjY2Vzc18AOQU9c2VjcmV0LQBGBS14eXomXG5wYXRpZW50PTQ1NiZcbmV4cGlyZXNfaW46IDM2MDBcbi4uLlxufQCBQgkAgmwFWwBPBgBhBiByZXNwb25zZV0AgwgUQQAkBgBfByBkYXRhIHZpYSBGSElSIEFQSQCBYQpSUzogR0VUIC9maGlyL1AAgREGLzQ1NlxuAIMfCACDVAU6IEJlYXJlciAAgT0QAIJqBVIAgRwIe3Jlc291cmNlVHlwZTogIgBKByIsICJiaXJ0aERhdGUiOi4uLn0KCgoKCgoKCgoK&s=default

**Comment by jmandel** [comment]
Perfect. I've performed some quick updates at:

[Edit Link](http://www.websequencediagrams.com/?lz=bm90ZSBsZWZ0IG9mIEFwcDogVXNlciBoYXMgbGF1bmNoZWQgYXBwXG5mcm9tIGFuIEVIUlxub3Igc3RhbmRhbG9uZSBmbG93CgBEBXJpZ2gAQApSZXF1ZXN0IGF1dGhvcml6YXRpb24KQXBwLT4-RUhSIEF1dGggU2VydmVyOiAgUmVkaXJlY3QgdG8gABkFUzogAB4Fb3JpemUAUQ8ALhFBdXRoZW50aWNhdGUgYW5kAGwJZSBBcHAAgQoUIE9uIGFwcHJvdmFsCgCBAA8tPj4AHgYAgQkMYXBwOnIAgR4HX3VybD9jb2RlPTEyMyYuLi4AgVEGAIFEElBPU1QgL3Rva2VuACcJAIEsIENyZWF0ZSAAMAU6XG57XG5hY2Nlc3NfAEIFPXNlY3JldC0ATwUteHl6JlxucGF0aWVudD00NTYmXG5leHBpcmVzX2luOiAzNjAwXG4uLi5cbn0AgVQSAINsBVsAWAYAagYgcmVzcG9uc2VdAIM-FEEAJAYAaAcgZGF0YSB2aWEgRkhJUiBBUEkAgXwKUlM6IEdFVCAvZmhpci9QAIEaBi80NTZcbgCDTAgAhAoFOiBCZWFyZXIgAIFGEACDDgVSZXNvdXJjZQCEHwcgAIMQBntyABAHVHlwZTogIgBXByIsICJiaXJ0aERhdGUiOi4uLn0KCgoKCgoKCgoK&s=default)

![Updated imiage](http://www.websequencediagrams.com/cgi-bin/cdraw?lz=bm90ZSBsZWZ0IG9mIEFwcDogVXNlciBoYXMgbGF1bmNoZWQgYXBwXG5mcm9tIGFuIEVIUlxub3Igc3RhbmRhbG9uZSBmbG93CgBEBXJpZ2gAQApSZXF1ZXN0IGF1dGhvcml6YXRpb24KQXBwLT4-RUhSIEF1dGggU2VydmVyOiAgUmVkaXJlY3QgdG8gABkFUzogAB4Fb3JpemUAUQ8ALhFBdXRoZW50aWNhdGUgYW5kAGwJZSBBcHAAgQoUIE9uIGFwcHJvdmFsCgCBAA8tPj4AHgYAgQkMYXBwOnIAgR4HX3VybD9jb2RlPTEyMyYuLi4AgVEGAIFEElBPU1QgL3Rva2VuACcJAIEsIENyZWF0ZSAAMAU6XG57XG5hY2Nlc3NfAEIFPXNlY3JldC0ATwUteHl6JlxucGF0aWVudD00NTYmXG5leHBpcmVzX2luOiAzNjAwXG4uLi5cbn0AgVQSAINsBVsAWAYAagYgcmVzcG9uc2VdAIM-FEEAJAYAaAcgZGF0YSB2aWEgRkhJUiBBUEkAgXwKUlM6IEdFVCAvZmhpci9QAIEaBi80NTZcbgCDTAgAhAoFOiBCZWFyZXIgAIFGEACDDgVSZXNvdXJjZQCEHwcgAIMQBntyABAHVHlwZTogIgBXByIsICJiaXJ0aERhdGUiOi4uLn0KCgoKCgoKCgoK&s=default)

**Comment by jmandel** [comment]
I think this is superceded by #16. Please re-open if I'm wrong.

**Comment by bakerdb** [comment]
You're right.  I thought about joining them, but #16 actually suggests a change to the profiles.  So decided to start anew.

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 16, 2015, at 2:31 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is superceded by #16<https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/16>. Please re-open if I'm wrong.
