### ISSUE TITLE
Separate Authz Server and Resource Server actors

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#14]
Refs:  RFC6749; RFC 681
Risk Assessment Row:  2

Threat:  Misinterpretation of OAuth 2.0 framework specification and threat model results in insecure implementation

Description:  Authorization profiles assign actions relating to issuance of access tokens and refresh tokens to "authorization server" and actions relating to use of access token to retrieve a resource as "resource server."

Recommended Change:  Clarify the actions of the OAuth 2.0 actors using the references “EHR Authorization Server” and “EHR Resource Server" in profiles.  Revise diagram to show EHR resource server and EHR authorization server as separate actors.

**Comment by jmandel** [comment]
Thanks @bakerdb! Can you confirm that [this document](https://docs.google.com/spreadsheets/d/1YdrQ3LLAxOxB5eJmTt1wnHjmSD6mVW6QUXbtl8_MF9c/edit) is the up-to-date risk assessment matrix that we're referring to?

**Comment by bakerdb** [comment]
Sorry!  I just finished cleaning up the risk assessment today -- removed all of the rows that did not contain a recommended change.  I just uploaded the revised doc to the Argonaut folder.  I tried putting it into the Risk Assessment folder, but for some reason I could not.  Feel free to move it.  The file name has today's date, so it'll be easy to see.  The refs in the Github recommendation corresponds to the rows in this spreadsheet.

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 13, 2015, at 2:34 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @bakerdb<https://github.com/bakerdb>! Can you confirm that this document<https://docs.google.com/spreadsheets/d/1YdrQ3LLAxOxB5eJmTt1wnHjmSD6mVW6QUXbtl8_MF9c/edit> is the up-to-date risk assessment matrix that we're referring to?

**Comment by jmandel** [comment]
Addressed through PRs including #31
