### ISSUE TITLE
End-user authorization

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#15]
Ref:  RFC6749 (10.2)
Risk Assessment Row:  3
Description:  Current profiles indicate that asking the end user to authorize the client is "optional." No information is included regarding how the AS requests authorization from the end user, or what information is provided to the end user.  
Recommendation:  Revise the first two paragraphs under "EHR [AS] Evaluates Authorization Request" to the following:
"The decision rules and process are up to the EHR AS.  The EHR AS will enforce rules based on local policy, and optionally will ask the end-user to authorize the app to access that user’s EHR information.  If an EHR launches the app for an authenticated user who has explicitly requested the launch, asking for the end user's authorization is optional; else the user's authorization SHOULD be requested.    

To obtain end-user authorization, the EHR AS authenticates the identity of the end-user (the method of authentication is outside the scope of this profile) and provides the user information regarding the client, and the resource, scope, and time for which access is being requested.   The end-user responds by either granting or denying the access request."

**Comment by jmandel** [comment]
Merged changes in through PR #28
