### ISSUE TITLE
502 Bad Gateway when sign up new account for Smart Sandbox

### ISSUE THREAD

**Issue by leanawen** [smart-on-fhir/smart-on-fhir.github.io#156]
Hi, 
I get the "502 Bad Gateway" message when signing up a new account for Smart Sandbox online (https://sandbox.smarthealthit.org/#/start). I wonder if this is a temporary server down or Sandbox does not accept new users? 
I am quite new to SMART sandbox, and I am not quite sure whether this is the right place to post the issue. Please let me know if you can direct me to a right place to post this issue. 
Thank you very much.
Jingran

**Comment by isaacvetter** [comment]
Hey @leanawen , 

As you suspected, this github site is not the right place to get support for that sandbox. But [this google group](https://groups.google.com/forum/#!forum/smart-on-fhir) is the right place. 

Further, Travis did say that they were doing [some maintenance work](https://groups.google.com/forum/#!topic/smart-on-fhir/Gx6pTMpbF_A) over the weekend.

At any rate, you should repost your question to that google group and I think this ticket should be closed.

Isaac

**Comment by leanawen** [comment]
Hi @isaacvetter, Thank you very much for the information. I will repost my question to the Google group.
