### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#16]
Ref:  RFC6749; RFC6819
Risk Assessment Row:  2
Description:  Current profiles combine OAuth2 Authorization Server and Resource Server actors into one "EHR" actor, which creates ambiguity in interpretation.
Recommendation:  Replace sequence diagram in confidential client authorization profile to the following:  
![new_confidentialv4](https://cloud.githubusercontent.com/assets/10760477/6648217/7707f182-c994-11e4-9bfa-9bb18698230c.png)

[Link to image](http://www.websequencediagrams.com/cgi-bin/cdraw?lz=bm90ZSBsZWZ0IG9mIEFwcDogVXNlciBoYXMgbGF1bmNoZWQgYXBwXG5mcm9tIGFuIEVIUlxub3Igc3RhbmRhbG9uZSBmbG93CgBEBXJpZ2gAQApSZXF1ZXN0IGF1dGhvcml6YXRpb24KQXBwLT4-RUhSIEF1dGggU2VydmVyOiAgUmVkaXJlY3QgdG8gABkFUzogAB4Fb3JpemUAUQ8ALhEAIAkgQXBwXG4obWF5IGluY2x1ZGUgZW5kLXVzZXIAew4pAIEfFCBPbiBhcHByb3ZhbAoAgRUPLT4-AB4GAIEeDGFwcDpyAIEzB191cmw_Y29kZT0xMjMmLi4uAE0VRXhjaGFuZ2UgY29kZSBmb3IgYWNjZXNzIHRva2VuCgCCGgYAgg0SUE9TVCAvAB8FAFsJAIFxJGVudGljYXRlIGFwcACCJSBDcmVhdGUAgQMGOlxue1xuAIEVBl8AgRYFPXNlY3JldC0AgSMFLXh5eiZcbnBhdGllbnQ9NDU2JlxuZXhwaXJlc19pbjogMzYwMFxuLi4uXG59AII4EgCEZQVbAIFtDCByZXNwb25zZV0AhDcUQQCCHQYAaAcgZGF0YSB2aWEgRkhJUiBBUEkAgiwKUmVzb3VyY2UAhFAJR0VUIC9maGlyL1AAgScGLzQ1NlxuAIRSCACFEAU6IEJlYXJlciAAgVMQAIRkEwBQEVJldHVybgCBBQZyAHYIAIQVBgCEPgUAgQMPAIF2B3sAIwhUeXBlOiAiAIEWByIsICJiaXJ0aERhdGUiOi4uLn0KCgoKCgoAAQU&s=default)

**Comment by bakerdb** [comment]
The link to edit is http://www.websequencediagrams.com/?lz=bm90ZSBsZWZ0IG9mIEFwcDogVXNlciBoYXMgbGF1bmNoZWQgYXBwXG5mcm9tIGFuIEVIUlxub3Igc3RhbmRhbG9uZSBmbG93CgBEBXJpZ2gAQApSZXF1ZXN0IGF1dGhvcml6YXRpb24KQXBwLT4-RUhSIEF1dGggU2VydmVyOiAgUmVkaXJlY3QgdG8gABkFUzogAB4Fb3JpemUAUQ8ALhEAIAkgQXBwXG4obWF5IGluY2x1ZGUgZW5kLXVzZXIAew4pAIEfFCBPbiBhcHByb3ZhbAoAgRUPLT4-AB4GAIEeDGFwcDpyAIEzB191cmw_Y29kZT0xMjMmLi4uAE0VRXhjaGFuZ2UgY29kZSBmb3IgYWNjZXNzIHRva2VuCgCCGgYAgg0SUE9TVCAvAB8FAFsJAIFxJGVudGljYXRlIGFwcACCJSBDcmVhdGUAgQMGOlxue1xuAIEVBl8AgRYFPXNlY3JldC0AgSMFLXh5eiZcbnBhdGllbnQ9NDU2JlxuZXhwaXJlc19pbjogMzYwMFxuLi4uXG59AII4EgCEZQVbAIFtDCByZXNwb25zZV0AhDcUQQCCHQYAaAcgZGF0YSB2aWEgRkhJUiBBUEkAgiwKUmVzb3VyY2UAhFAJR0VUIC9maGlyL1AAgScGLzQ1NlxuAIRSCACFEAU6IEJlYXJlciAAgVMQAIRkEwBQEVJldHVybgCBBQZyAHYIAIQVBgCEPgUAgQMPAIF2B3sAIwhUeXBlOiAiAIEWByIsICJiaXJ0aERhdGUiOi4uLn0KCgoKCgoAAQU&s=default

**Comment by jmandel** [comment]
@bakerdb I've started a new github branch to track changes to the docs. So far I've:

1. Streamlined the authorization specs so we have only a single page (covers both "confidential" and "public" client profiles, since they only differ in a couple of spots).

2. Updated the sequence diagram to the one you've listed here. 

Live preview of the rendered docs:  [`argonaut-dev`](http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/)

Specific changes committed in: https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/4aaa95e900b1c69a8f254577a4bfde7183ac32af

**Comment by bakerdb** [comment]
Great, Josh!  Looks really good!

Should I continue to submit my issues against the "confidential authorization profile," or should I reference the sections in this revision?

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 18, 2015, at 6:58 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


@bakerdb<https://github.com/bakerdb> I've started a new github branch to track changes to the docs. So far I've:

 1.  Streamlined the authorization specs so we have only a single page (covers both "confidential" and "public" client profiles, since they only differ in a couple of spots).

 2.  Updated the sequence diagram to the one you've listed here.

Live preview of the rendered docs: argonaut-dev<http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/>

Specific changes committed in: 4aaa95e<https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/4aaa95e900b1c69a8f254577a4bfde7183ac32af>

**Comment by jmandel** [comment]
Please go ahead and reference these, if it's not too much trouble. This
should give us a good base for the upcoming set of revisions

**Comment by bakerdb** [comment]
I agree.  And will give me a chance to become intimately familiar with the revised profile.

- Dixie


Dixie Baker
Office: 310-791-9671
Cell: 310-279-2579


On Mar 18, 2015, at 11:25 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:

Please go ahead and reference these, if it's not too much trouble. This
should give us a good base for the upcoming set of revisions

**Comment by jmandel** [comment]
Great. Closing this as finished.
