### ISSUE TITLE
Security: in the EHR Launch sequence, Applications should validate that `iss` matches something on file

### ISSUE THREAD

**Issue by nwhatt** [smart-on-fhir/smart-on-fhir.github.io#165]
I'm working through integrating SMART EHR launch sequences with our version of SSO. 

It occurred to me that a developer could very easily expose a number of sensitive things in the EHR launch flow if they don't validate `iss` on the inbound request, which the sample app does not do [see app.js](https://github.com/smart-on-fhir/sample-apps-stu3/blob/master/authorize/app.js).

The attacker would need the launch URL for the app. 

1.  Send a launch GET to the target app with the attacker's `iss` parameter set
2. If the app has a client secret - at this point it could be compromised because basic auth will hit the attackers endpoint.
3. The attacker can then provide OAuth 2 endpoints and a profile for a target user. 
4. The attacker is now (theoretically) an authenticated user in the target application, and can take any action that that user can take (open a real patient's chart, for example)

This is hard to mitigate in the SMART on FHIR spec, and ultimately depends on the application security, but I think there is room for a "best practices" type of article. 

Thoughts?

**Comment by JohnMoehrke** [comment]
There is a IETF RFC standard (Informative) on OAuth 2.0 - Threat Model and
Security Considerations
  see https://tools.ietf.org/html/rfc6819

John

John Moehrke
Principal Engineering Architect: Standards - Interoperability, Privacy, and
Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
M +1 920-564-2067
JohnMoehrke@gmail.com
https://www.linkedin.com/in/johnmoehrke
https://healthcaresecprivacy.blogspot.com
"Quis custodiet ipsos custodes?" ("Who watches the watchers?")

**Comment by whitehatguy** [comment]
John,

Phishing client credentials via a counterfeit authorization server isn't one of the threats listed in the OAuth 2.0 threat model.  The authors most likely did not assume that a given client would be dealing with a multiplicity of authorization servers.  This potential problem is unique to SMART on FHIR.  The only countermeasure listed in that RFC that could apply here is the use of an HMAC (section 4.3.3).

**Comment by jmandel** [comment]
Thanks @nwhatt, @whitehatguy! It's quite correct that any client with the possibility of leaking sensitive information (keys, PII, etc.) needs to validate an `iss` on incoming EHR Launch requests. Our JS demo apps don't generally have these properties, but our spec should certainly be clear on this point.  I should note that we're in the process of standardizing this spec through HL7 at https://github.com/HL7/smart-app-launch and have a long list of editorial changes still to make.

It would be good to propose a specific recommendation in the text of the "EHR launch sequence" of that repo.

**Comment by nwhatt** [comment]
Moved to https://github.com/HL7/smart-app-launch/issues/230
