### ISSUE TITLE
Clarification needed around refresh_token expiration time

### ISSUE THREAD

**Issue by rdingwell** [smart-on-fhir/smart-on-fhir.github.io#168]
Currently the authorization section of the documentation states the following: 

"Access tokens SHOULD have a valid lifetime no greater than one hour, and refresh tokens (if issued) SHOULD have a valid lifetime no greater than twenty-four hours.  Confidential clients may be issued longer-lived tokens than public clients." 

The 24 hour life of the refresh_token in this context really seems geared toward public clients, not confidential clients, but it's not clear in that regard.  The purpose, IMO , for offline_access is true long lived refresh_tokens for confidential clients, where long lived, at least to me, is longer than a 24 hour period of time.  

I would suggest a modification to the current wording to be more in line with something like the following: 

Access tokens SHOULD have a valid lifetime no greater than one hour. Refresh tokens (if issued) to public clients SHOULD have a valid lifetime no greater than twenty-four hours.  Refresh tokens (if issued) to confidential clients will have a valid lifetime as determined by the Authorization Server.

**Comment by jmandel** [comment]
Thanks! This has been addressed in the HL7 ballot resolution process at https://github.com/hl7/smart-appl-launch. We'll be finalizing these resolutions and publishing an updated version of the spec in short order.
