### ISSUE TITLE
How to manage data in app coming from different types of profiles?

### ISSUE THREAD

**Issue by leo9223** [smart-on-fhir/smart-on-fhir.github.io#169]
As we make an app on smart-on-fhir platform, if we connect that app to some random FHIR server and get patient resources from that server. There is a possibility that the patient resources coming from that server comply with their own custom patient profile (StructureDefinition).

How to handle this situation in the smart-on-fhir app?

Will the app only deal with the default fields available in the patient resource in the FHIR spec?
or
The app will first get the profile of the patient resource, and then it will act according to the profile of the resource?

**Comment by jmandel** [comment]
When fetching a Patient resource from a server, a client will always receive a resource that's valid according to the FHIR Patient StructureDefinition. Additional profiles, like the one Argonaut has produced for use in the context of the Meaningful Use Common Clinical Data set, build on this profile; so there should never be a contradiction. The only fields present will be the ones FHIR defines, though there may be _extension_ elements conveying additional information.

In general, https://groups.google.com/forum/#!forum/smart-on-fhir is a great place for questions related to this spec -- and http://chat.fhir.org/for live chat.
