### ISSUE TITLE
(editorial) Missing question

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#20]
[New Profile]
Description:  The introductory paragraph ends with a colon.

Recommendation:  Add "Does the app have the capability to “keep a secret?”  after colon

**Comment by jmandel** [comment]
Do you want to just go ahead and propose little edits like this as pull requests? You should be able to click the "edit this page" link from the sidebar of http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/

**Comment by bakerdb** [comment]
Yes, that would work great!

How about I submit all editorial changes this way and use the "issues" approach for changes tracable to the risk assessment?

- Dixie


Dixie Baker
Office: 310-791-9671
Cell: 310-279-2579


On Mar 19, 2015, at 9:38 AM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want to just go ahead and propose little edits like this as pull requests? You should be able to click the "edit this page" link from the sidebar of http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/

**Comment by jmandel** [comment]
@bakerdb You can just use the "edit this page" process for both kinds of changes. They'll both be captured as "pull requests", which appears in our issues list. Here's a fake example of a pull request that I created (and which I'll reject):

https://github.com/smart-on-fhir/smart-on-fhir.github.io/pull/21

**Comment by bakerdb** [comment]
Sure!  Didn't realize that's what a "pull request" was!

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 19, 2015, at 12:37 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want to just go ahead and propose little edits like this as pull requests? You should be able to click the "edit this page" link from the sidebar of http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/

**Comment by jmandel** [comment]
Great. I'll close this issue for now then. Feel free to re-open if you need!
