### ISSUE TITLE
What does "recommended" mean for "aud" parameter of authz request?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#33]
@bakerdb The current draft says:

![image](https://cloud.githubusercontent.com/assets/313089/6816524/ca80c936-d251-11e4-83e5-b5123686422d.png)

But it's unclear what this means. For which parties (apps or servers) is this "recommended"? I'd imagine some servers would *require* it, which means it's really not optional for apps. If we want to go this route, and offer this mitigation, then we need to say something stronger about it, from the app's perspective.

**Comment by bakerdb** [comment]
Yes, i should be "required."  Can you make this change?

-Dixie
