### ISSUE TITLE
Update to sequence diagram

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#36]
The sequence diagram does not show the refresh_token included in the return from the Authorization Server, nor is the refresh_token exchange included.  
Also, for confidential clients, authentication is required for both requesting authorization and for exchanging an access token for FHIR content.  In the attached sequence diagram, I have corrected these omissions.  

Link to this diagram is http://www.websequencediagrams.com/?lz=bm90ZSBsZWZ0IG9mIEFwcDogVXNlciBoYXMgbGF1bmNoZWQgYXBwXG5mcm9tIGFuIEVIUlxub3Igc3RhbmRhbG9uZSBmbG93CgBEBXJpZ2gAQApSZXF1ZXN0IGF1dGhvcml6YXRpb24KQXBwLT5FSFIgQXV0aCBTZXJ2ZXI6ICBSZWRpcmVjdCB0byAAGQVTOiAAHgVvcml6ZQBQDwAuEQAgCSBBcHBcbihtYXkgaW5jbHVkZSByAIEAB2ZvciBlbmQtdXNlcgCBBg4pAIEqFCBPbiBhcHByb3ZhbAoAgSEPLT4AHQYAgSkMYXBwOnIAgT4HX3VybD9jb2RlPTEyMyYuLi4ATBVFeGNoYW5nZSBjb2RlAIEaBWFjY2VzcyB0b2tlbgoAghIYUE9TVCAvAB8FAIIYCQCCVgU6IEJhc2ljIHdvMzk4YndvLi4uAHwIAHESAIIuFWVudGljYXRlIGFwcACCUyBDcmVhdGUAgSYGOlxue1xuAIE4Bl8AgTkFPXNlY3JldC0AgUYFLXh5eiZcbnBhdGllbnQ9NDU2JlxuZXhwaXJlc19pbjogMzYwMFxucmVmcmVzaAA6B2J3M3NvY2k4MzJsODVcbi4uLlxufQCCchdbAIItDCByZXNwb25zZV0AhQEUQQCCXQYAgQUHIGRhdGEgdmlhIEZISVIgQVBJAIUWClJlc291cmNlAIUbCUdFVCAvZmhpci9QAIFEBi80NTZcbgCCdBBlYXJlciAAgXAQAIUvEwBQEVJldHVybgCBBQZyAHYIAIRVBgCEfQUAgQMPAIR_B3sAIwhUeXBlOiAiAIEWByIsICJiaXJ0aERhdGUiOi4uLn0Ahx8GAIdhDQCCCAcAhEgGAIMMBwCHMBwAgloIAIMlBQCEXkQAg10aMTg1AIUUI1IAhC8GAIYtDgCDeC4KCgoKCgABBQ&s=default
![new_confidentialv5](https://cloud.githubusercontent.com/assets/10760477/6909011/e7cca9c0-d6f6-11e4-84e3-c81335c1eb7f.png)

**Comment by jmandel** [comment]
I don't disagree with any of these details, but... the more details we include in a diagram like this, the harder it becomes to see the big picture. We may be hitting the limit of how much we can reasonably show in a sequence diagram (e.g. HTTP headers are probably a bit much). 

What would you think about having a set of sequence diagrams like:

 * Launch sequence
 * Authorization sequence
 * Refresh sequence

?

**Comment by bakerdb** [comment]
I like this idea!  The launch sequence cries out for a diagram!  Perhaps make the 3rd one something like "Usage sequence" to include both exchange for FHIR resource and refresh.

And yes, it is a bit complex.  As for the HTTP headers, I was just trying to follow what you had done in the original diagram.  I agree that we can simplify.

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Mar 30, 2015, at 4:11 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't disagree with any of these details, but... the more details we include in a diagram like this, the harder it becomes to see the big picture. We may be hitting the limit of how much we can reasonably show in a sequence diagram (e.g. HTTP headers are probably a bit much).

What would you think about having a set of sequence diagrams like:

 *   Launch sequence
 *   Authorization sequence
 *   Refresh sequence

?

**Comment by jmandel** [comment]
I believe this has now been addressed through #40 #41 #42 #43 -- closing.
