### ISSUE TITLE
Launch Sequence Diagram 

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#37]
I've taken a stab at creating a sequence diagram for the launch sequences.  In so doing, I've concluded that some of the detail currently in the "overview" section would fit more logically in the detailed description, but I can handle that later.  First, I wanted you to look over the diagram.

![launchseqv1](https://cloud.githubusercontent.com/assets/10760477/6985911/1f59afe8-d9ed-11e4-861a-5cd9a80dc8c2.png)

Link:  http://www.websequencediagrams.com/?lz=YWx0IEVIUiBMQVVOQ0gKCm5vdGUgbGVmdCBvZgAUBVNlc3Npb246IExhdW5jaCBhcHAgZnJvbSBFSFIKCgAXCyAtPiBCcm93c2VyOiAgT3BlbiBuZXcgd2luZG93OyBcbiBSZWRpcmVjdCB0byBBcHAgVVJMCgArByAtPiBBcHAAXQlub3RpZmljYXRpb24sIFxuIGluY2x1ZGluZyBjb250ZXh0CkFwcCAtPgCBOAVGSElSIFNlcnZlcjogR2V0IGF1dGhvcml6ADsFIGVuZHBvaW50cwCBKgUAIgsAbQkgQQAkDWFuZCB0b2tlAC8MAIIMDQCBJgVTdGFydCBPQXV0aDIgc2VxdWVuY2UAgQsMQXV0aACBDglSZXF1ZXMAgQwPLCBwYXNzaW5nIGFsbwCBUgogCmVuZCAKCmFsdCBTVEFOREFMT05FAIMcCACDFg0AgmkJAIMYB3N0YW5kYWxvbmUgYXBwAIJOEQCDOwsAgRGBMACCLBYAgycFAIQLCGVuZAoKCgoKCgABBQAGBQ&s=default

**Comment by jmandel** [comment]
I like the general idea, but I'm having trouble following the actors ("EHR Session", "Browser", and "App" aren't really actors on equal footing). For example, in a standalone launch on mobile, it doesn't make sense to talk about a "Browser" performing a "launch app" action. There may simply be no browser involved in that context.

It might be easier to  leave "Browser" out of the actors list and then just describe a pair of launch flows like:

## Launch Flow

```
title App Launch Flow

alt EHR Launch
EHR Session ->> App: Redirect to {app:launch_uri}?launch=123
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch:123&state=abc&...

alt Standalone Launch
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch/patient&state=abc&...
```

## Authz Flow

```
title Authorization Flow

App ->> EHR Authz Server: Redirect to {ehr:authorize_uri} (see Launch Flow)
Note  right of EHR: On approval
EHR->>App: Redirect to {app:redirect_uri}?code=abc
App->EHR: POST /token?code=123
Note right of EHR: Create token:\n {\naccess_token=secret-token-xyz&\npatient=456&\nexpires_in: 3600\n...\n}
}
EHR->App: [access token response]
```

**Comment by bakerdb** [comment]
"Browser" is intended to simplify the "user agent" actor in OAuth2, which can be a browser, window, iframe, mobile device -- whatever launches the app.  Because the text says that in the EHR launch, the EHR "initiates a launch sequence by opening a new browser widget, window, or iframe," I thought we should show it.  Also, it provides a base from which to launch the standalone app.  Would "user agent" be better?

On the other hand, your comment re mobile raises the question of whether we should simply delete the sentence saying that the EHR "initiates a launch sequence by opening a new new browser widget..."  since it would apply only to a hosted app.

The rest seems fine to me.  However, earlier you said you'd like to simplify the text in the sequence diagrams?

-Dixie




Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Apr 3, 2015, at 11:11 AM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the general idea, but I'm having trouble following the actors ("EHR Session", "Browser", and "App" aren't really actors on equal footing). For example, in a standalone launch on mobile, it doesn't make sense to talk about a "Browser" performing a "launch app" action. There may simply be no browser involved in that context.

It might be easier to leave "Browser" out of the actors list and then just describe a pair of launch flows like:

Launch Flow

title App Launch Flow

alt EHR Launch
EHR Session ->> App: Redirect to {app:launch_uri}?launch=123
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch:123&state=abc&...

alt Standalone Launch
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch/patient&state=abc&...


Authz Flow

title Authorization Flow

App ->> EHR Authz Server: Redirect to {ehr:authorize_uri} (see Launch Flow)
Note  right of EHR: On approval
EHR->>App: Redirect to {app:redirect_uri}?code=abc
App->EHR: POST /token?code=123
Note right of EHR: Create token:\n {\naccess_token=secret-token-xyz&\npatient=456&\nexpires_in: 3600\n...\n}
}
EHR->App: [access token response]

**Comment by bakerdb** [comment]
Actually, when I looked at this graphic (below), it occurred to me that these should be two different sequences -- one with an "EHR Session" actor and one without -- because "EHR Session" is not an actor at all in the standalone sequence...

[cid:31C0B1E5-376C-4E77-BDC2-FC17F5164B1D]
Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Apr 3, 2015, at 11:11 AM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the general idea, but I'm having trouble following the actors ("EHR Session", "Browser", and "App" aren't really actors on equal footing). For example, in a standalone launch on mobile, it doesn't make sense to talk about a "Browser" performing a "launch app" action. There may simply be no browser involved in that context.

It might be easier to leave "Browser" out of the actors list and then just describe a pair of launch flows like:

Launch Flow

title App Launch Flow

alt EHR Launch
EHR Session ->> App: Redirect to {app:launch_uri}?launch=123
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch:123&state=abc&...

alt Standalone Launch
App -> EHR FHIR Server: GET /metadata
EHR FHIR Server -> App: [Conformance statement including OAuth 2.0 endpoint URLs]
App ->> EHR Authz Server: Redirect to {ehr:authorize_uri}?scope=launch/patient&state=abc&...


Authz Flow

title Authorization Flow

App ->> EHR Authz Server: Redirect to {ehr:authorize_uri} (see Launch Flow)
Note  right of EHR: On approval
EHR->>App: Redirect to {app:redirect_uri}?code=abc
App->EHR: POST /token?code=123
Note right of EHR: Create token:\n {\naccess_token=secret-token-xyz&\npatient=456&\nexpires_in: 3600\n...\n}
}
EHR->App: [access token response]

**Comment by jmandel** [comment]
I certainly agree with that point (two separate sequences would make the distinction clearer).

As for depicting the browser (aka "user agent"), I think we should consider *not* visualizing this as its own actor in the sequence diagram. e.g. see https://www.salesforce.com/us/developer/docs/api_rest/Content/intro_understanding_web_server_oauth_flow.htm (or http://docs.smarthealthit.org/authorization/confidential/ for that matter). It might be something that we track off to the side, or just leave implicit in the according to the "redirect" steps.

**Comment by bakerdb** [comment]
Removed browser as separate actor.
Separated into two separate diagrams (EHR and Standalone), inserted into profile, and initiated a pull request.  So I am closing this issue.

**Comment by jmandel** [comment]
Thanks @bakerdb  -- could you just list the PR number here (preceded by "#") to close the loop? I don't see it yet...

**Comment by bakerdb** [comment]
I don't see the pull request numbers.  In fact, the pull-requests symbol on my page says "0."

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Apr 9, 2015, at 4:10 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @bakerdb<https://github.com/bakerdb> -- could you just list the PR number here (preceded by "#") to close the loop? I don't see it yet...

**Comment by jmandel** [comment]
Here are all the open PRs:
https://github.com/smart-on-fhir/smart-on-fhir.github.io/pulls?q=is%3Aopen+is%3Apr

Each has a number below its title (e.g the one I've screen-shotted below is 35):
![image](https://cloud.githubusercontent.com/assets/313089/7079415/e78a98de-ded8-11e4-8989-e62b2d3d75c2.png)

Is it possible you're looking for PRs on @bakerdb's fork (rather than on @smart-on-fhir's repository)?

At https://github.com/bakerdb/smart-on-fhir.github.io/ I do indeed see the expected zero:
![image](https://cloud.githubusercontent.com/assets/313089/7079431/0b1ba6d0-ded9-11e4-811c-a1a00b94f299.png)


But at https://github.com/smart-on-fhir/smart-on-fhir.github.io I see three:
![image](https://cloud.githubusercontent.com/assets/313089/7079436/1d5f99aa-ded9-11e4-940e-feecf3120535.png)

The problem is that none of these three appear to have the content you're describing (or, if one does, I'm missing it).

**Comment by bakerdb** [comment]
Yes, I see.

-Dixie


Dixie B. Baker, Ph.D.
Senior Partner
Martin, Blanck and Associates
Office (Redondo Beach, CA):  310-791-9671
Mobile:  310-279-2579

On Apr 9, 2015, at 4:55 PM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are all the open PRs:
https://github.com/smart-on-fhir/smart-on-fhir.github.io/pulls?q=is%3Aopen+is%3Apr

Each has a number below its title (e.g the one I've screen-shotted below is 35):
[https://cloud.githubusercontent.com/assets/313089/7079415/e78a98de-ded8-11e4-8989-e62b2d3d75c2.png]<https://cloud.githubusercontent.com/assets/313089/7079415/e78a98de-ded8-11e4-8989-e62b2d3d75c2.png>

Is it possible you're looking for PRs on @bakerdb<https://github.com/bakerdb>'s fork (rather than on @smart-on-fhir<https://github.com/smart-on-fhir>'s repository)?

At https://github.com/bakerdb/smart-on-fhir.github.io/ I do indeed see the expected zero:
[https://cloud.githubusercontent.com/assets/313089/7079431/0b1ba6d0-ded9-11e4-811c-a1a00b94f299.png]<https://cloud.githubusercontent.com/assets/313089/7079431/0b1ba6d0-ded9-11e4-811c-a1a00b94f299.png>

But at https://github.com/smart-on-fhir/smart-on-fhir.github.io I see three:
[https://cloud.githubusercontent.com/assets/313089/7079436/1d5f99aa-ded9-11e4-940e-feecf3120535.png]<https://cloud.githubusercontent.com/assets/313089/7079436/1d5f99aa-ded9-11e4-940e-feecf3120535.png>

The problem is that none of these three appear to have the content you're describing (or, if one does, I'm missing it).
