### ISSUE TITLE
Authz Diagram

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#38]
Since this is a different diagram, I'm starting a new issue.  I started with your suggestion from Issue #37 regarding the Authorization sequence, cleaned it up (e.g., it had both "EHR" and "EHR Authz Server" as separate actors, though "EHR" is not an actor in this one), added explanatory notes, and also added id_token and refresh_token to the authz return.  Here's the result:

![authzseqv1](https://cloud.githubusercontent.com/assets/10760477/6989435/1735836e-da10-11e4-9f0b-9a1df47f2729.png)

Link:  http://www.websequencediagrams.com/?lz=bm90ZSByaWdodCBvZiBBcHA6IFJlcXVlc3QgYXV0aG9yaXphdGlvbgpBcHAgLT4-IEVIUiBBdXRoeiBTZXJ2ZXI6IFJlZGlyZWN0IHRvIHtlaHI6ADEIZV91cml9IChzZWUgTGF1bmNoIEZsb3cpCgBnDgBAEkEAOQggQXBwXG4obWF5IGluY2x1ZGUgcgCBFwdmb3IgZW5kLXVzZXIAgR0OKQpOb3RlIABFHE9uIGFwcHJvdmFsCgCBQRAgLT4-AIIBBwCBTQthcHA6cgCBYgcAgVIFP2NvZGU9YWJjAIE_DwCCPgVFeGNoYW5nZSBjb2RlAIEmBWFjY2VzcyB0b2tlAIJHBS0-AII3ElBPU1QgLwAeBQBYBjEyMyZzZWNyZXQ9MzgyOTU3amkAghclZW50aWNhdGUgYXBwAIIHBgCCUhtDcmVhdGUAgRQGOlxuIHtcbgCBJwZfAIEoBT0AewYtAIE1BS14eXomXG5pZAAIFHczayZcbnBhdGllbnQ9NDU2JlxuZXhwaXJlc19pbjogMzYwMCZcbnJlZnJlc2gALRVwcSBcbi4uLlxufQp9AIMGFACFHAVbAIJBDCByZXNwb25zZV0&s=default

**Comment by jmandel** [comment]
This looks good. Quick comment:

In the first step it might help to give a hint of some of the parameters (e.g. `?client_id=something&...`). The back-reference to "See Launch Flow" might be confusing, because the launch flow actually refers to something before this step, rather than at this step.

**Comment by bakerdb** [comment]
I made the suggested changes to the diagram, and inserted it into the profile as a pull requested.  So I think we can close this issue.

**Comment by jmandel** [comment]
OK -- just to close the loop on this: which PR is this inserted into? You can say "#300" or whatever and that will create a link.
