### ISSUE TITLE
Retrieval & Refresh Diagram

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#39]
Here's a draft of a diagram showing use of access token to retrieve FHIR resource, and exchange of refresh token for new access token.

![resourceretrievalv1](https://cloud.githubusercontent.com/assets/10760477/6989969/a0f909ac-da17-11e4-98ad-dde597b87ee3.png)

Link:  http://www.websequencediagrams.com/?lz=bm90ZSByaWdodCBvZiBBcHA6IEFjY2VzcyBwYXRpZW50IGRhdGEgCkFwcC0-PkVIUiBGSElSIFNlcnZlcjogUmVkaXJlY3QgdG8ge2VocjpmaGlyX3VyaX0_YQBCBV90b2tlbj1zZWNyZXQtY29kZS14eXoKAGkOAEQTdHVybgBlBnJlc291cmNlIHRvIGFwcAoAdQ8tPgCBMAV7AB8IVHlwZTogIlAAgTgGIiwgImJpcnRoRGF0ZSI6Li4ufQB2BmxlZgCBYREAgSYFIGV4cGlyZXMAgRQPAIIVBVJlcXVlc3QAIgdyZWZyZXNoAIIQC0F1dGh6AIITCQCCCxJhdXRoegCCGAYANgcAghEOAIInBS13cHEmAIIqBj0zODI5NTcAghsTAFwOQXV0aGVudGljYXRlIGFwcCAKTgATH0NyZWF0ZSBuZXcAgXAGOlxuIHtcbgCDIBQAgQ8GeHl6JlxuSUQAgR4GAIEiDzNrJlxuAIQpBz00NTYmXG4Agj8HX2luOiAzNjAwXG4AgVMfXG4uLi5cbn0KfQoAg14FAIJADACDXQdbAIRNBgCCdglzcG9uc2VdCgoKCgoKAAEFCg&s=default

**Comment by bakerdb** [comment]
I've inserted this diagram into patch-10, so I am closing this issue.

**Comment by jmandel** [comment]
OK, that means PR #34 -- thanks!
