### ISSUE TITLE
Requesting offline access for an access token.

### ISSUE THREAD

**Issue by whitehatguy** [smart-on-fhir/smart-on-fhir.github.io#46]
Currently, there doesn't seem to be a way for a client application to convey that it desires permanent access on behalf of a user versus short-lived access.  A given application may have both modes of operation, and a given EHR administrator may wish to restrict the "offline access" scenario without impeding the short-lived access use case.  Additionally, I don't think it is reasonable to configure an authorization server to always hand out offline access tokens for both scenarios, as that's something you'd likely want to prompt the user to explicitly approve, and the user might be using a workflow that only requires short-lived access.

If I had to make a proposal, I would propose a special scope of "offline".  This scope's semantic would  indicate that the resulting grant is for use by the client application when the user is offline.  It would allow an authorization server to disambiguate whether a given request requires short-lived or long-lived access.

**Comment by jmandel** [comment]
Can using take a look at how we're document the `offline_access` score at
http://docs.smarthealthit.org/authorization/confidential/ ?

(I'm guessing you may be looking at the Argonaut branch, which still needs
these details incorporated. Let me know if the language in the an overall
addresses your concerns.)

**Comment by whitehatguy** [comment]
Josh -- thanks much, I was looking at the wrong branch. Do you feel the documentation should explicitly state that it is designed for scenarios where a client retains access after the user's session has been terminated/expired?

**Comment by bakerdb** [comment]
I don't think it's "designed for" these scenarios.  It's "designed" to support a wide range of policies that a resource holder might want to enforce.  In some circumstances, the fact that the client retains access after the user's session has been terminated may not be viewed as a good thing.  This is one reason why the Argonaut profile includes refresh tokens.  If an app holds a bearer token, it's good until it expires, at which point a refresh token can be used to obtain a new bearer token -- or not, depending upon the rules the authorization server is enforcing at that time.  I don't think this explanation belongs in the app profile, but we do plan to include it in our best practices for server implementers.

**Comment by whitehatguy** [comment]
@bakerdb  - Can you provide an explicit example of a policy a resource holder might want to enforce for a scope named "offline_access" other than where a client retains access after the user's session has been terminated/expired?  

I'm cognizant of the fact that refresh tokens provide value in scenarios other than an offline usage scenario (specifically, they can be used as a mechanism to verify if a user's session is still present).

**Comment by jmandel** [comment]
@bakerdb I think apps do need a way to communicate when they *want* a long-term access token, at authorization time. OIDC does this with the `offline_access` claim. The name isn't perfect, but it is already part of that standard and others use it as a way of asking for refresh tokens (@jricher has made this point to us, too). 

So @bakerdb: do you have an objection to our adding the `offline_access` in our argonaut branch, as we've done in the master branch? If you do object, what alternative would you propose?

I think @whitehatguy  and I are on the same page here...

**Comment by bakerdb** [comment]
I agree that apps need a way to request long-term access, and the OIDC offline_access claim is well suited to this purpose.  However, to answer @whitehatguy's question, yes I do have a couple of policy recommendations because, as the OIDC spec notes, offline_access does pose greater privacy risk than access with the user present.  So first, I think we should strongly suggest (to AS implementers) that explicit consent be obtained.  And second, I would restrict this capability to confidential clients only (a policy consistent with Google's policy -- https://developers.google.com/identity/protocols/OAuth2WebServer.

So I am in favor of adding offline_access, but would not do it exactly as you've done it in the master branch.

**Comment by jmandel** [comment]
Okay, that's a good start. It doesn't quite address the issue of how to
obtain a refresh token on a mobile device (since in our profiles that's
still a public client). Do you agree this is a requirement? And if so, do
you have thoughts about how we should approach this, given the constraints
you've outlined?

**Comment by whitehatguy** [comment]
- I'm in agreement that explicit consent should be obtained for offline access.
- I'm not in agreement that such offline access should be restricted to confidential clients.  Google allows native client applications to utilize refresh tokens until revoked by the user [1] (Google states "The client ID and client secret obtained from the Developers Console are embedded in the source code of your application. In this context, the client secret is obviously not treated as a secret.").   An EHR administrator should have control over such behaviors.  An explicit example where an EHR administrator would want to require an application to use confidential credentials is when said client stores large numbers of offline access tokens centrally on a server.

I'm still not sure what position (if any) the spec has on the use of refresh tokens for short-lived access.

[1] https://developers.google.com/identity/protocols/OAuth2InstalledApp

**Comment by bakerdb** [comment]
Mobile apps can obtain refresh tokens if the AS decides to provide one along with the access token.  So I think its sufficient to give mobile apps the ability to request long lifetimes, and to allow the AS to decide whether to fulfill this request by sending a refresh token along with the access token.

Given the risk, I think it's prudent to restrict the ability to REQUEST refresh tokens, via offline_access, to authenticated apps.  For example, if a patient wants to request not only that her EHR be transmitted to her PHR, but that any updates be transmitted as well, it would seem logical for her to request that the portal app have offline_access to her EHR.  I think most mobile apps also have server based interfaces that could be used for this purpose.  But I can think of no compelling need for a mobile app to have this capability.  

@whitehatguy, I'm not suggesting that mobile apps should not be able to use refresh tokens, which is what the URL you cite addresses.  I'm just suggesting that the ability for an app to REQUEST a refresh token (offline_access) should be restricted to confidential clients.  The Google URL I cited (https://developers.google.com/identity/protocols/OAuth2WebServer) addresses the use of offline_access, not just refresh tokens.

**Comment by jmandel** [comment]
@bakerdb 

> Mobile apps can obtain refresh tokens if the AS decides to provide one along with the access token.

But this is exactly the question at hand: how does the mobile app communicate to the AS that it would like a refresh token? The goal is that an `offline_access` scope would convey this. Of course the AS's policy is still in play here: it can decide to ignore/deny this request and just issue an access token with no refresh token. Do you see this as a problem? It feels like a clean separation of concerns to me...

**Comment by bakerdb** [comment]
If a mobile app wants long-term access, it can request an expiry value of say 6 months.  The AS then might choose to issue it an access token and a refresh token instead.  

I do agree that this is a policy issue, but this seems fairly important to me.  And I can think of no compelling requirement for a mobile app to have indefinite access to an EHR.  As I said earlier, most mobile apps also have web servers capable of authenticating themselves.  I think that makes much more sense than asking people to authorize something this risky from a untrustworthy mobile device.  

BTW, how does an end-user withdraw offline_access if she changes her mind later?

**Comment by jricher** [comment]
There's no way within OAuth for an app to specify the expiry that it wants for its tokens. It's entirely up to the auth server policy and the client can't even make a request here without extending the standard. On the other hand, the `offline_access` scope conveys this already. You want a mobile app to have continued access to the EHR because there's not the same kind of "session" information or other login that a web-based confidential client would have. 

You can do confidential clients in mobile apps easily enough, it just requires that you use dynamic client registration. Each instance registers itself and gets a separate `client_id` and `client_secret`. There are downsides to this, but it's quite viable and used in practice in a number of places.

To withdraw `offline_access`, a user would simply go to the server and revoke access to that client. In many implementations, this also revokes outstanding tokens for that client.

**Comment by bakerdb** [comment]
Ah, I was (obviously) mis-thinking that expiry was one of the parameters an app could request.  

@jmandel, I agree that we need to enable offline_access for both confidential and mobile clients, including the recommendation that end-user authorization be obtained.  I also think we should include in our advice to AS implementers that they need to provide an API through which users can withdraw their authorizations.  

@jricher, all Argonaut apps are pre-authorized and registered.  However, that does render them capable of protecting a secret.  So mobile apps are considered public apps.

**Comment by jmandel** [comment]
@bakerdb Yes, I think this is the right treatment of `offline_access`. I'l create a PR for this to capture the change. When you say that 

> AS implementers... need to provide an API through which users can withdraw their authorizations

What's the use case here? If it's just to support *users*, then all we need to say is that AS implementers need to support a **UI** by which users can withdraw authorizations. No?

**Comment by bakerdb** [comment]
An API will enable the app that requested offline_access to also provide a means for individuals to cancel this access.  This is important since many users won't have a clue where to find the UI.

- Dixie


Dixie Baker
Office: 310-791-9671
Cell: 310-279-2579


On Apr 21, 2015, at 6:52 AM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


@bakerdb<https://github.com/bakerdb> Yes, I think this is the right treatment of offline_access. I'l create a PR for this to capture the change. When you say that

AS implementers... need to provide an API through which users can withdraw their authorizations

What's the use case here? If it's just to support users, then all we need to say is that AS implementers need to support a UI by which users can withdraw authorizations. No?

-

**Comment by jmandel** [comment]
It could be useful in some cases, but asking apps to be responsible for canceling their own authorization is not a general-purpose solution (after all, the apps would all have to implement the functionality independently and correctly, and it requires meticulous self-policing). The natural place for this kind of functionality is within the patient "portal" (or whatever online place the patient authenticates to when approving an app, even if it's not a full-blown portal). 
 
The equivalent is, for apps authorized to access my Google account with long-term permissions, it's *Google* that provides the following page: https://security.google.com/settings/security/permissions where I can view and revoke permissions. It's not each of the 20 apps that I've given permissions to.

**Comment by jricher** [comment]
There's no standardized way to manage a server's saved access grant decisions, which is more of a server policy decision about whether or not to prompt the user again. I know of a few implementations that have an API to manage that, but it's usually handled by a UI like Josh suggested. That way the server can be sure of user authentication and perform other checks.

There is the [Token Revocation](https://tools.ietf.org/html/rfc7009) spec that allows an app to tell the server to throw out tokens that it's done with, which is helpful.

**Comment by bakerdb** [comment]
You'll recall that my preference is to limit offline_access to confidential apps -- as Google does.  This makes it easy for users to both authorize and cancel authorization thru the same portal.

References to what is "usually" done don't take into consideration that we're talking about access to personal health and medical information here.  I'm very uncomfortable with the idea that an Android app might get long-term offline access to EHR information -- making it difficult to withdraw that access only increases my discomfort.

My preference is to limit offline_access to confidential clients (which could be a portal associated with a mobile app) and a UI for withdrawing that access.

- Dixie

Dixie Baker
Office: 310-791-9671
Cell: 310-279-2579


On Apr 21, 2015, at 7:16 AM, Josh Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:


It could be useful in some cases, but asking apps to be responsible for canceling their own authorization is not a general-purpose solution (after all, the apps would all have to implement the functionality independently and correctly, and it requires meticulous self-policing). The natural place for this kind of functionality is within the patient "portal" (or whatever online place the patient authenticates to when approving an app, even if it's not a full-blown portal).

The equivalent is, for apps authorized to access my Google account with long-term permissions, it's Google that provides the following page: https://security.google.com/settings/security/permissions where I can view and revoke permissions. It's not each of the 20 apps that I've given permissions to.

-

**Comment by whitehatguy** [comment]
@bakerdb  -- the scope of offline_access only applies to Google's confidential apps because all grants issued to public (native) clients are issued as permanent-until-revoked (or abused).  Google treats all access requested by such clients as requests for offline access on behalf of the user.  This makes apps such as those that use your Google Drive for storage possible without having to sign in each and every time you want to use your files.

**Comment by jmandel** [comment]
@bakerdb I thought when you wrote:

> I agree that we need to enable offline_access for both confidential and mobile clients,

... that you'd support doing this with the `offline_access` scope. But then you said 

> my preference is to limit offline_access to confidential apps

So what alternative do you propose for mobile clients? (Dynamic registration of mobile apps with a different client_id per-device is certainly  possible; it's what the OIDF HEART group is doing. But it does add a number of moving parts and it would be important to justify this decision with respect to our threat analysis.)

My preference is to specify that confidential and public clients can both ask for offline_access  with the same semantics. Of course AS policy can always refuse to grant a refresh token at an point.
