### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by wanghaisheng** [smart-on-fhir/smart-on-fhir.github.io#47]
http://docs.smarthealthit.org/authorization/scopes-and-launch-context/
section User-level scopes ,the final rows

Manage all resources on behalf ot he authorizing user
user/*.read user/*.write 	
Note that the permission is broader than our goal: with this scope, an app can add not only blood pressures, but other observations as well.

why  blood pressures?

**Comment by p2** [comment]
Those are example goals. One example is that your app wants to be able to add blood pressure readings to the user's record. The solution is to use `patient/Observation.write`, **but** that allows to write _any_ observations, not only blood pressure observations.

Does this help?

**Comment by jmandel** [comment]
(To say this directly: in FHIR, Observation is used to capture lab results, blood pressures, and other kinds of clinical data. So asking for `Observation.read` is a broad permission.)

Note that our current reference implementation only handles *very* broad permissions like `user/*.read`, `patient/*.read` -- not resource-level permissions.

**Comment by wanghaisheng** [comment]
get that one.this section goes to illustrate how to use these user-level scope params instead of patient-level.here you state the goal is "Manage all resources on behalf ot he authorizing user(here is a typo too)",if "user/*.read user/*.write" means manage all resources ,how could any permission broader than this one?

**Comment by jmandel** [comment]
Let me try that again:

1. Imagine an app *wants* to access only Blood Pressures
2. But it *asks for* (and receives) `Observation/*.read`

--> at this point, the app has broader permissions than it really needed. For example, it can access lab result observations in addition to blood pressures.

**Comment by wanghaisheng** [comment]
totally agree and understand this .though Observation is a resource type but it is a highly abstract one.many concept like blood type or vital sign could be represented by observation.your implement could not distinguish these subtle difference.

**Comment by jmandel** [comment]
Also, fixed that "ot" typo, thanks. https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/7665b87255b306aa719b5741ae80e5e644955f1d
