### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by wanghaisheng** [smart-on-fhir/smart-on-fhir.github.io#50]
I am going to tranlate your SMART  doc and localize some sdk ,is this ok?

**Comment by jmandel** [comment]
Yes. Please be aware that it's a work in progress and there will likely be
breaking changes over time, but the specs are available for you to use and
translate!

**Comment by wanghaisheng** [comment]
I might ask a  stupid question here. any thoughs about HIPAA in smart and related sdk

**Comment by jmandel** [comment]
Well, these APIs are certainly meant to be usable in the context of HIPAA
covered entities, for clinician and patient applications. But we don't have
any HIPAA specific functionality per se.
