### ISSUE TITLE
Prefix OAuth 2 parameters

### ISSUE THREAD

**Issue by kpshek** [smart-on-fhir/smart-on-fhir.github.io#55]
Currently, the SMART specification defines scopes like `patient/*.read` and `launch`. In the current Argonaut branch, it is mentioned that scopes may need to be represented as URIs and defines a URI pattern to follow.

Per [rfc6749](http://tools.ietf.org/html/rfc6749):

> Unregistered vendor-specific parameter extensions that are not
>    commonly applicable and that are specific to the implementation
>    details of the authorization server where they are used SHOULD
>    utilize a vendor-specific prefix that is not likely to conflict with
>    other registered values (e.g., begin with 'companyname_').

For consistency, and to ensure SMART's scopes do not conflict with other scopes the authorization server may be handling, all SMART scopes should be prefixed. Going with the current Argonaut documentation, this would be requiring that all scopes are prefixed with `http://smarthealthit.org/fhir/scopes`. For reference, [here](http://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#parameters) are the currently registered OAuth 2 parameters.

On a related topic, SMART should also prefix the SMART specific parameters that are returned with the access token -- both for consistency and to avoid possible collisions with other token parameters the authorization server may be returning. However, [rfc6749](http://tools.ietf.org/html/rfc6749#section-5.1) does not explicitly require or recommend this:

> The client MUST ignore unrecognized value names in the response.  The
>    sizes of tokens and other values received from the authorization
>    server are left undefined

// cc @whitehatguy since some of this is also called out in [your white paper](https://github.com/whitehatguy/healthcare-authorization):

> A name-spacing mechanism to prevent collisions with other specifications that utilize scopes.

@jmandel - Let me know if this sounds good. If so, I will start on a pull request to update the argonaut documentation around this

**Comment by jmandel** [comment]
Thanks for bringing this up @kpshek ! On the subject of scopes, I think the risk that a scope like `patient/Patient.read` is going to conflict coincidentally with a non-SMART scope is low. But I don't object to this change (even while I do cringe at the verbosity it introduces to our scope strings).

As for parameters in our access token response: one possibility is to "hide" them all behind a common property, e.g.:

```
{
  "access_token": "xyz",
  ...
  "http://smarthealthit.org/fhir/context": {
    "patient": "123",
    "encounter": "456", 
    "need_patient_banner": ...
  }
}
```

I have a sense this may be nicer to work with than:

```
{
  "access_token": "xyz",
  ...
  "http://smarthealthit.org/fhir/context/patient": "123",
  "http://smarthealthit.org/fhir/context/encounter": "456", 
  "http://smarthealthit.org/fhir/context/need_patient_banner": ...
  }
}
```

Thoughts?

**Comment by kpshek** [comment]
:+1: - I like how your parameter proposal both minimizes the verbosity as well as ensures uniqueness.

**Comment by daliboz** [comment]
I tested this a bit with the java nimbus library because I was concerned about how some of the libraries handle this, but it seems ok for both the server and client side. It just means that some entries in a map are themselves maps (and I assume this would also be true in a client js library).

I like grouping them together.

**Comment by whitehatguy** [comment]
@jmandel's proposal for access token responses seems optimal and avoids the possibility of any name collisions in current or future attributes that might be chosen by the specification.  

Kevin's other comment was regarding whether to namespace scopes to avoid collisions.  While I think the majority of values as defined are sufficiently unambiguous, there's the question of whether collisions with other protocols will come into play.  For example, had I written an OAuth server prior to the development of OpenID Connect that defined "profile" as a scope, to add OpenID support I would have had to either:

- Accept OIDC's scope as a semantic equivalent of my own.
- Change my contract with client consumers to have a new name for my custom "profile" scope. 

While the majority of what is currently defined would have a low probability of conflicting with something defined by another open protocol (perhaps "launch" may not have this characteristic?), I think this is why UMA [1], Google, and others chose to go down the road of using URIs as scopes and is probably worth calling out.  Notably, the IANA doesn't have a registry for scope values [2], so it appears to be somewhat of an honor system for specs to avoid colliding with other specs.

[1]:https://datatracker.ietf.org/doc/draft-hardjono-oauth-umacore/
[2]:http://hg.openid.net/connect/issue/558/since-oauth-provides-no-iana-registry-for

**Comment by kpshek** [comment]
So as I've been applying these changes to the SMART documentation and examining the concrete implications of this change, here is what an application launch URL would now be:

```
https://ehr/authorize?
            response_type=code&
            client_id=app-client-id&
            redirect_uri=https%3A%2F%2Fapp%2Fafter-auth&
            launch=xyz123&
            scope=http%3A%2F%2Fsmarthealthit.org%2Ffhir%2Fscopes%2Flaunch%20http%3A%2F%2Fsmarthealthit.org%2Ffhir%2Fscopes%2Fpatient%2FObservation.read%20http%3A%2F%2Fsmarthealthit.org%2Ffhir%2Fscopes%2Fpatient%2FPatient.read%20http%3A%2F%2Fopenid.net%2Fspecs%2Fopenid-connect-core-1_0%2Fopenid%20http%3A%2F%2Fopenid.net%2Fspecs%2Fopenid-connect-core-1_0%2Fprofile&
            state=98wrghuwuogerg97
```

Internet Explorer (10 and earlier), _our favorite browser_, [allows for a maximum of 2083 characters in a URL](https://support.microsoft.com/en-us/kb/208427). For the curious, [here are details behind this limitation in IE](http://blogs.msdn.com/b/ieinternals/archive/2014/08/13/url-length-limits-in-internet-explorer.aspx).

The aforementioned URL is 498 characters. Considering that actual application redirect URLs will be much longer than the contrived domain above, client ids will likely be 36 character UUIDs, and the requested scopes vary in number, the resultant URL will be much longer.

As such, while I agree that using URIs for scopes would be a good thing, I believe that in practice this may result in URLs which exceed 2083 characters -- especially when the OAuth 2 server is authorizing other scopes in which a SMART application may request and in cases of very complex SMART applications which request access to many different FHIR resources. Therefore, I would propose we:

* Prefix the SMART launch* scopes with `smart_`
* Prefix the FHIR launch scopes with `fhir_`
* Prefix OpenID Connect scopes with `openid_`

I feel satisfied that these prefixes will sufficiently manage the risk against collisions while being mindful of the resultant URL length.

```
https://ehr/authorize?
            response_type=code&
            client_id=app-client-id&
            redirect_uri=https%3A%2F%2Fapp%2Fafter-auth&
            launch=xyz123&
            scope=smart_launch%20fhir_patient%2FObservation.read%20fhir_patient%2FPatient.read%20openid_openid%20openid_profile&
            state=98wrghuwuogerg97
```

Again using the original example, these proposed changes now result in a URL length of 261 characters (nearly half the size).

If we wanted to, we could make the following further optimizations to reduce the size:
* Abbreviate .read and .write with .r and .w in the FHIR scopes (I propose we implement this now)
* Abbreviate the FHIR resource names in the FHIR scopes (of course we have to come up with this set of abbreviated values)

Thoughts @jmandel / @daliboz / @whitehatguy / @grahamegrieve ?

**Comment by jmandel** [comment]
Thanks for this attention to detail!

A couple of  clear points: we don't prefix the OIDC scopes with anything: they're defined in the OIDC standard. And I wouldn't try to abbreviate FHIR resource names. 

It's also worth noting that this approach won't address Grahame's original request for scopes that are URIs. 

But IE10 compatibility does matter, clearly. Do you know what limitations IE11+ impose, by the way?

**Comment by kpshek** [comment]
>Do you know what limitations IE11+ impose, by the way?

I have not verified this (I don't run Windows) and I don't know how authoritative this is, but [this StackOverflow comment](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#comment48135535_417184) mentions IE11 handling URLs with "~3600" characters.

**Comment by whitehatguy** [comment]
If I may suggest a compromise to try and satisfy all audiences:

- urn:fhir:{scope}
- urn:smart:{scope}

These aren't currently reserved with the IANA, are only slightly larger (4 characters), and would create compliant absolute URIs.  They just aren't URLs.

**Comment by jmandel** [comment]
After talking with Grahame he's not actually that concerned with having URIs and would be happy enough just to have SMART use bare scopes. So the key issue is uniqueness. 

One other point is that we don't have any natural "smart" vs "fhir" scope distinction, which this proposal has introduced,  and it seems to complicate the picture a bit. 

Is it a step backwards to just suggest taking our existing scopes and prefixing all of them with "smart/"? That would mean `smart/launch`, `smart/patient/Observation.r`, etc. (I do like the abbreviated read/write syntax.)

**Comment by grahamegrieve** [comment]
Right. having URIs would be 'nice', but there's no way that it's justified
if we have space constraints



On Fri, May 15, 2015 at 6:40 PM, Josh Mandel <notifications@github.com>
wrote:

> After talking with Grahame he's not actually that concerned with having
> URIs and would be happy enough just to have SMART use bare scopes. So the
> key issue is uniqueness.
>
> One other point is that we don't have any natural "smart" vs "fhir" scope
> distinction, which this proposal has introduced, and it seems to complicate
> the picture a bit.
>
> Is it a step backwards to just suggest taking our existing scopes and
> prefixing all of them with "smart/"? That would mean smart/launch,
> smart/patient/Observation.r, etc. (I do like the abbreviated read/write
> syntax.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/55#issuecomment-102320015>
> .
>



-- 
-----
http://www.healthintersections.com.au / grahame@healthintersections.com.au
/ +61 411 867 065
