### ISSUE TITLE
Update Authorization example to include "aud" parameter

### ISSUE THREAD

**Issue by PBernhardt** [smart-on-fhir/smart-on-fhir.github.io#59]
The authorization guidance here: http://fhir-docs.smarthealthit.org/argonaut-dev/authorization/

Includes an image with an example of the request made to the authorization url. This image should be replaced with one that includes the required "aud" parameter.

**Comment by jmandel** [comment]
We do write "..." to indicate that there are more parameters than we can show in the sequence diagram -- but if it would be helpful to add this one, we can!

**Comment by PBernhardt** [comment]
Yeah, not a showstopper by any means, but only mentioned because it's a required input. It was clear enough to me what was needed after reading the documentation carefully.

**Comment by jmandel** [comment]
Fair enough -- addressed in https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/ca956f3d7b5c659cc4da86ab2838739a37677049
