### ISSUE TITLE
Invalid link/page for new apps

### ISSUE THREAD

**Issue by dsoprea** [smart-on-fhir/smart-on-fhir.github.io#65]
The page at [Sandbox - Account Setup](http://docs.smarthealthit.org/sandbox/account) has a link ("register new apps") that is no longer valid:

*You can register a new account for our public sandbox or manage your existing account by visiting our [account self-service](https://service.smarthealthit.org) tool. Once you have an account in our system, you will be able to use our authorization service and [register new apps](http://docs.smarthealthit.org/sandbox/howto) on it.*

**Comment by jmandel** [comment]
Thanks -- fixed with https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/a72e5229330ab4a64ccafa05564cb38c24599005!
