### ISSUE TITLE
Re-authorizing after launch

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#71]
>   If an app has to re-request access to a resource whose authorization was originally obtained via a 
>   launch, how does it request that?  Currently, scopes only define single-resource access via launch scopes, or access to the entire set available to the user.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-71

**Comment by jmandel** [comment]
This is an area that needs further treatment. I would suggest the following behavior:

1. When using a refresh token a client can omit `scope` (as described in the [OAuth 2.0 spec, section 6](https://tools.ietf.org/html/rfc6749#section-6)) to ask for the same scopes as it got with the original access token.

2. When this occurs, the app gets a new access token with exactly the same permissions at the old one. I would propose that the extra context (id_token, patient, location, need_patient_banner, etc) should be omitted in the access token response; they are effectively fixed from the initial launch, and it would be wrong to return an id_token indicating that the user had re-authenticated if this was not, in fact, the case.

3. If an app desires narrower permissions upon refreshing its access token, it may provide a `scope` parameter. The value must be a strict subset of the originally requested scopes. The server SHOULD respect the requested narrowing, and MUST ignore any additional scopes requested at this point. Note that context-related scopes (e.g. `launch` or `launch/patient`) are ignored, if provided. The original authorization has fixed the context for this token, and the context is now immutable.

Is this fair?

**Comment by bakerdb** [comment]
I agree with this approach.

**Comment by whitehatguy** [comment]
In summary - if an app has a requirement to re-obtain access for a launched context, it must request online_access or offline_access and utilize the refresh mechanism already defined.  We should make sure that the requirements around refresh tokens indicates that any launch context should be retained by the authorization server when issuing such refresh tokens, but such launch claims do not need to be returned in token responses for refresh tokens.  

Should we explicitly note that applications cannot re-request access for a specific context through other means, and the user must re-launch an application if they have logged out and the app was not provided offline_access?  I know this question will get asked by client developers -- maybe just include it in an FAQ?

**Comment by jmandel** [comment]
Yes, the summary is right. The clarification you've proposed sounds like an
appropriate FAQ kind of question to me (but if you have a spot where you
want to address it directly in the spec, that's fine).

**Comment by bakerdb** [comment]
I don't understand what use case you're thinking of when you say "applications cannot re-request access for a specific context through other means."  

I think the explanation of online_ access and offline_access should make it clear that unless the application is provided offline_access, it terminates when the user logs off.

**Comment by whitehatguy** [comment]
Say an application wanted to track your history of which patients you have accessed for quicker access - if the application is only authorized for patient/... scopes (instead of user/...), it would never be capable of re-requesting authorization to access that specific patient's records once the user is logged out.  The only option for the user to access that record through the client app again would be via one of the launch flows.
