### ISSUE TITLE
Versioning of SMART spec

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#72]
>   Should this specification touch on versioning for future versions?

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-72

**Comment by bakerdb** [comment]
Yes.

**Comment by jmandel** [comment]
Yes. We should attempt to use [semantic versioning](http://semver.org/) from the perspective of a client.  So bugfixes increment a patch version; new features increment the minor version; and breaking changes increment the major version. Then a server supporting `X.Y.Z` should be compatible with any app supporting `X.y.*` where `y` <= `Y`. 

Thoughts?

**Comment by whitehatguy** [comment]
I've been chewing on this for a while - I'm going to throw out some proposals here to see to see what sticks:

- Include the version number in EMR-initiated launch requests
- Apps  __SHOULD__ check this value to determine if they are compatible and indicate to the user where incompatibility exists.
- Only optional features would be added in minor version releases, thus allowing for backwards-compatibility between clients and servers on the same major version.
- For workflows initiated by apps, the SMART version could also be advertised in the conformance document; apps __SHOULD__ check that version for compatibility before initiating an authorization request to the server.

Other thoughts: an authorization server could support different major versions; it might be wise to allow advertising of multiple versions (or even perhaps different endpoints per-version?)  An alternative to advertising the version in the conformance document would be add an extension parameter to the authorization request to allow the authorization server to make a determination as to how to satisfy the request.

**Comment by jmandel** [comment]
Matt, I notice you want a version number in the launch request itself; is
there a reason we need it there instead of int he conformance statement?

If we can get away with it, my preference would be to add a "SMART on FHIR
Authorization Protcocol Version ID" to the Conformance statement, right
next to our existing discovery extensions. As Matt suggests, we'd use semver
<http://semver.org/> conventions so that backwards-incompatible changes
bump the major number, new features bump the minor version number, and bug
fixes bump the patch.

**Comment by bakerdb** [comment]
It seems to me that since the app developer will have used x version of the spec to build the app, that version should be included in the app launch request so that the authz server will know what version was implemented in the app vs. the current version (given in the conformance statement).  Knowing this may influence the authz server's decision about whether to authorize access, and how that access might be restricted due to security vulnerabilities in an earlier version.   

If it's only in the conformance statement, then the onus is on the app developer and app implementer to make sure the app is kept current with the current version.

**Comment by jmandel** [comment]
Given that we haven't had any issue with this, and I'm reluctant to add
more parameters to the launch URL on speculation alone.

**Comment by whitehatguy** [comment]
No particular issues with not sending the version in protocol message; it does lobby a passivity requirement on the version advertised in the conformance document (if we changed the discovery mechanism in the conformance statement, but still want to advertise the new version to old apps, the old mechanism would need to be retained for a period of time.)  I personally think that's acceptable.
