### ISSUE TITLE
Question: scopes for whole-system interaction

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#73]
>   Do any of these scopes allow for whole system interactions?

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-73

**Comment by jmandel** [comment]
I see we haven't documented it in, but my intention was to support `system/` scopes in addition to `user/` scopes, and `patient/` scopes. These would be values like `system/Patient.read` allowing an app to read/search all patient records in "the system".

**Comment by whitehatguy** [comment]
I was actually inquiring as to the whole system interaction as defined by FHIR [1], such as searching across all resources (perhaps that would be different than being able to read all resources?).  I wasn't sure about the transaction interaction either... would that be a reserved right such that only certain client applications could start transactions on the server?

[1]: http://www.hl7.org/implement/standards/fhir/http.html

**Comment by jmandel** [comment]
We never draw a direct correspondence (I think) between scopes and FHIR
interactions. But FHIR's instance level "read" and type level "search" are
both enabled with SMART ".read" scopes. System level read interactions like
history or search should, I suppose, also be enabled by ".read" scopes, but
they would only reveal individual resources that the supplied access token
is authorized to see. Just like the type level search does.

Transactions (and the new non-transactional "batch"es) are just groups of
other interactions performed all at once, so I don't think they should
require any special permissions.

Operations, on the other hand, may produce arbitrary side effects. This is
an area that will need additional authorization primitives. (Of course,
there are other areas too, like profile-level permissions rather than just
resource level permissions.)

**Comment by bakerdb** [comment]
What access rights are allowed for specific clients and users would be based on institutional policy, with the associated rules enforced by the AS.
