### ISSUE TITLE
Should styling/ux context be defined separately?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#75]
>   Should the additional optional bits about intent and styling be included as a core part of the specification, or be handled as an optional extension specification?  If those bits will change frequently, it may make sense to keep them separate.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-75

**Comment by kpshek** [comment]
I don't see the intent parameter changing in the future. As it is now, this is an inherently vendor specific attribute and it's inclusion in the specification serves to standardize on the namely of the parameter only. So, I think leaving this in the core specification is fine. Out of curiosity, what are the use(s) of this today that prompted it's inclusion in SMART?

I do think the smart_style_url parameter will change so moving this into an extension specification makes sense.

**Comment by bakerdb** [comment]
I think it depends upon what we intend this specification to become.  If we see this as ultimately becoming an HL7 specification for authorizing app access to EHR data, then I think we should disassociate it from "SMART on FHIR," and create an abbreviated SMART on FHIR implementation guide that points to this more formal specification.  In such case, I suggest including the style guidance in the SMART on FHIR implementation guide, but keeping it out of the HL7 specification.   If on the other hand, this is intended to remain a SMART on FHIR document, then I think it's fine to include it.

**Comment by jmandel** [comment]
I don't disagree with the notion of separating out some bits of launch
context (like styling hints). But I would hope that HL7 is interested in
standardizing the whole package as a working solution -- so I think the
conclusion here is okay but I don't quite agree with the analysis.

**Comment by whitehatguy** [comment]
I'll plan on assembling a second document then with the styling components, unless there's other objections then.
