### ISSUE TITLE
Do EHRs need to be OIDC Identity Providers?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#76]
> Are we requiring EHRs to be identity providers, thus requiring them to implement section "15.1.  Mandatory to Implement Features for All OpenID Providers" for OpenID Connect?  This adds quite a bit to the EHR's requirements, and will require running EHRs through the OpenID Connect conformance features.  This also gets QUITE complicated if the EHR itself is an OpenID Connect relying party... it has to pass-through much of the functionality to the upstream OIDC IdP.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-76

**Comment by jmandel** [comment]
I agree this asks a lot of EHRs. Specifically, it asks EHRs to act as OIDC Identity Providers. But I don't know any way around this if we want to give apps a consistent way to launch, with awareness of end user identity. So I think the use case is very strong.

Do you see an alternative, @whitehatguy? Are you imagining simply removing this requirement, or somehow stripping it down by subsetting OIDC requirements?

**Comment by whitehatguy** [comment]
Let's start with this question:

"Will client applications protect their own resources outside of those protected by the authorization server __and__ desire to utilize the EHR as a means for authenticating users?"

If the answer is __"YES"__, then we need to ask the following question:

"Will it be required that all EHRs support this feature (to allow client applications to protect their own resources) initially?"

If the answer is __"NO"__, it still stands to reason that apps will need identity information purely for display context and auditing purposes.  For that, we could simply return the FHIR URL in the token response.  This change would also be helpful to other client applications that don't have the requirement to protect their own resources.  Authorization servers with OIDC support would still want to return the FHIR URL as part of a signed identity token in addition to any other base mechanism.

I'm fairly sure the answer to question 1 is "YES".  I don't have the answer to question 2, unfortunately.  Were there any deep-dives on this particular topic at either of the HL7 meetings?  It seems like there would be quite a bit to think about, particularly session management between these distributed actors.

**Comment by jmandel** [comment]
From the SMART perspective, the answer is YES to both. We aim to provide a
solid foundation for building diverse apps.

**Comment by whitehatguy** [comment]
As a follow up question, do the required elements of the OIDC core specification support all of the anticipated use cases?  I think at a minimum some portions of the discovery protocol get pulled in where the issuer value is different than the token endpoint URL.  Are the use cases documented somewhere at the moment (for instance, are EHRs intended to issue public identifiers to individuals for self-identification and discovery?)

**Comment by jmandel** [comment]
We haven't formally documented use cases, but @gimbalgambit can help describe some of the SureScripts use cases (where, for example, they want to know that the user who launches an app is a known SureScripts provider)

It's certainly the case that portions of the OIDC discovery protocol are invoked — for example, to validate the signature on an `id_token` JWT, a client must determine the issuer's JWK (presumably via discovery).

**Comment by bakerdb** [comment]
Use cases for the Argonaut Project are http://argonautwiki.hl7.org/images/e/ec/Argonaut_UseCasesV1-1.pdf

Phase 1 addressed use cases #1 through #4; phase 2 is focusing on #5.

**Comment by jmandel** [comment]
But none of these use cases (1-4) gets into the details of why/how the user's identity is communicated to the app. Matt's asking about the use case for OIDC (essentially, why do we need single sign-on).

**Comment by gimbalgambit** [comment]
Surescripts has a need to identify/authenticate the end user for a few reasons, including protecting our own resources as @whitehatguy spelled out. Auditing of end-user access and roles management is also part of why the OIDC support by the EHR is pretty important to our SMART apps.  There are specific identifiers (like the Surescripts Provider Identifier, SPI) that we assign in our management infrastructure that allows us to properly route external data to the correct SMART session or end-user via other means (like our secure messaging network).

**Comment by bakerdb** [comment]
The Argonaut Use Case document defines "EHR" very broadly --  "We use 'EHR' in a broad context inclusive of any system that holds and controls individually identifiable health information.  Each EHR system has the capability to mediate app requests for access and to authorize access to FHIR resources."  

Our intent was to include "EHR"s that may hold health data collected by a fitness center or personal health monitor.  Some of these "EHRs" outside the regulated healthcare environment could use an OID provider that was separate from the EHR.  I don't think our specification should require that the OID provider be the same as the AS provider.

**Comment by jmandel** [comment]
Hold on though -- first, let's get agreement on the use case that apps need
to know who their end users are, in order to properly manage their affairs.
Yes?

Assuming that's clear: are you then suggesting that apps would go though
two separate OAuth dances, one with "the ehr AS" and a second with "the ehr
Id server" (so the user would experience multiple flows, buy the values
from the two separate flows would nevertheless need to be precisely
aligned)?

**Comment by bakerdb** [comment]
Yes, I can envision a use case where an app uses an OID provider (e.g., Google+) to authenticate the end user, but only rarely needs to reach out to pull data from an EHR, at which point it uses the AS associated with the resource server holding the data to obtain an access token (without requesting an ID token).  In fact, I'm working on such an app now.

**Comment by jmandel** [comment]
But at this point you're not talking about the user's *EHR* identity --
you're talking about who they are on Google+. The issue is when you need
EHR claims (like an NPI number, or practitioner specialty) that G+ can't
provide.

**Comment by whitehatguy** [comment]
It sounds like this feature is important enough to need documented use cases, and flesh out the functional boundaries (for example - is there a session management function to govern single log-out, should EHRs support the use of a general discovery mechanism via hostname/email/acct syntax?)  I've heard some internal asks from one of our own solution development groups that they want to build solutions that protect their own resources but function with an external identity provider as well.

**Comment by jmandel** [comment]
Functioning with an external idp is a no-op for us, as far as I can
understand -- apps are always welcome to provide whatever functionality
they choose, including custom accounts, Sign in with Twitter, or whatever.
The question here is what guarantees the EHR will provide for the app.
SMART takes single sign-on to be a requirement.

I thought Argonaut was clear on this point, since we've been profiling
OIDC.

On Tue, Sep 1, 2015, 18:18 Matt Randall <notifications@github.com> wrote:

It sounds like this feature is important enough to need documented use
cases, and flesh out the functional boundaries (for example - is there a
session management function to govern single log-out, should EHRs support
the use of a general discovery mechanism via hostname/email/acct syntax?)
I've heard some internal asks from one of our own solution

groups that they want to build solutions that protect their own resources
but function with an external identity provider as well.

—
Reply to this email directly or view it on GitHub
<https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/76#issuecomment-136879666>.<img
src="
https://ci5.googleusercontent.com/proxy/xaA0uEgqQmNSSd755lwNhYW58mPm8H0_JGpqtKYqMhLZN5Fbf9jVFH7EtnW8yAbD69R8TqzSwXJvgXZKf8TMotnWRx07cidnuAcoo6AYE-m-oI3bwu3pJEonTRIaLbxGWHSsbLTls2XeXJqLppX4P6T_9VVFIg=s0-d-e1-ft#https://github.com/notifications/beacon/AATHAcVLY_vBTuOuD3EMsrme8XyWLFSMks5othuvgaJpZM4Fr-Te.gif
">

**Comment by bakerdb** [comment]
It seems to me that we're confusing two authenticated identities -- the identity the app uses for its own purposes, and the authenticated identity the authorization server needs to authorize the requested access.  Unless the app includes openid in the scope of its request, the authorization server does not return an OID token.  As our profile states, openid and profile are required parameters only "if app needs authenticated patient identity."  I don't think Argonaut cares what authenticated identity the app uses for its own purposes.

**Comment by bakerdb** [comment]
Thank you @whitehatguy for getting us back to the issue at hand.  I don't think our profile should dictate EHR architecture.

**Comment by jmandel** [comment]
@bakerdb The question here (as far as I can understand it) is precisely what happens when the app asks for scopes including `openid` and `profile`. My read is that @whitehatguy would like to know if we really *need* support for scopes like `openid` and `profile` at all, or whether we could get by without asking the EHR to act as an OIDC Identity Provider. In any case, we're talking about end-user identities here, and whether/how these are communicated to the app.

**Comment by bakerdb** [comment]
The question was "Are we requiring EHRs to be identity providers, thus requiring them to implement section "15.1. Mandatory to Implement Features for All OpenID Providers" for OpenID Connect?"  

I would state the requirement as something like "The authorization server MUST have the the capability to return an ID token when the app includes the openid parameter in its scope."  That doesn't mean the AS is required to "implement section 15.1..."  We've been careful not to dictate internal implementation.  So if the AS implements this capability by being the relying party to an OID provider outside the enterprise, that should be acceptable.  In fact, having a common source of identity across an OCHA might be a nice approach to the serious problem of managing patient identity.

**Comment by bakerdb** [comment]
I meant to type "OHCA" (Organized Health Care Arrangement) -- which may be a good use case to use here.

**Comment by jmandel** [comment]
No matter how the EHR implements it (whether they originate claims
directly, or pass through claims from an secondary IDP), the EHR is still
acting as an OIDC IDP in this context.

**Comment by whitehatguy** [comment]
Based on this conversation, let me float a couple of ideas just to get a baseline as to how much thought alignment we have:

- An EHR acts as a first-class identity provider, or, acts as a _proxy_ for an existing identity provider.
  - When acting as a proxy, the proxied identity provider has no awareness of SMART apps; any required user consent (for patient-facing apps) is managed through the EHR's authorization server.  In corollary, apps have no awareness of the proxied identity provider.
- Client apps must have some administrative capability for re-associating the URL "issuer" value if an organization changes their URLs.
- Client apps would use a SMART-defined resource for checking validity of the user sessions (e.g. "single log-out")?
  - "online_access" allows apps to effectively participate in a "session", but we really don't spell it out in the current specification. I'm not sure the [OIDC session management][1] draft spec covers our native apps at this point though unless we define a mechanism ourselves.  Single log-out is a major recurring conversation topic that I have with healthcare organizations, I feel we need a good story here.
- EHRs advertise keying endpoints through SMART-defined mechanisms, rather than OIDC discovery mechanisms?
- EHRs don't provide a UserInfo endpoint.  FHIR resources should instead be used to obtain user demographics.




[1]: http://openid.net/specs/openid-connect-session-1_0.html

**Comment by whitehatguy** [comment]
FYI, Mike Jones just wrote the first draft of the [OIDC back-channel log-out specification][1].  This might resolve part of my above question as to how to handle "single log-out" where the EMR (or client apps) are native.

[1]: http://openid.net/specs/openid-connect-backchannel-1_0-00.html

**Comment by bakerdb** [comment]
Re:  Client apps would use a SMART-defined resource for checking validity of the user sessions (e.g. "single log-out")?
>>I don't think such a resource currently exists.  @jmandel, who would define this resource?  

Re EHRs advertise keying endpoints through SMART-defined mechanisms, rather than OIDC discovery mechanisms?
>>I think this is true from a specification perspective.  But I don't think we want to create policy that prohibits OIDC discovery.  

Re EHRs don't provide a UserInfo endpoint. FHIR resources should instead be used to obtain user demographics.
>>Same here.  I don't think we want to create policy that prohibits an EHR from providing a UserInfo endpoint.  (especially given our broad definition of "EHR")

**Comment by whitehatguy** [comment]
I agree we shouldn't prohibit additional capabilities, but do we require or recommend them?  For example, if we intend that id_tokens can be verified by other actors outside of the client application, then it's a given that we have to require OIDC discovery via .well_known at the issuer URL.  It also puts a requirement on the client application that it performs the same discovery and verification, as now it is possible for the AuthN server to be independent of the AuthZ server.  If we do not have that need, and want a simpler mechanism for clients, then we would simply require that the issuer value be equal to the token URL.
