### ISSUE TITLE
Should patient- and provider-facing services use different FHIR base URLs?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#77]
>   In certain workflows, the authorization server will need to request the user to authenticate.  Since the mechanism used by providers and patients will likely be different, how do we disambiguate the nature of the access for the authorization server to appropriately send them to the right place to log in?  Since services for patients and providers might have different conformance properties, should it just be recommended that they are implemented as different FHIR base URLs? 

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-77

**Comment by kpshek** [comment]
This is an interesting question and something I had not considered. Do you have any examples of conformance property differences between patients and providers?

**Comment by kpshek** [comment]
> This is an interesting question and something I had not considered. Do you have any examples of conformance property differences between patients and providers?

Nevermind. In an offline conversation with @daliboz, she reminded me of all of the reasons that I should known. :smile: 

- The authorization server may differ in how it authenticates patients vs providers thereby requiring a different authorization server URL
- The FHIR resources offered may be different for patients vs providers. For instance, a FHIR server may offer writes of MedicationPrescription to providers but for patients it is just read.

**Comment by jmandel** [comment]
In practice, some systems will absolutely want to provide different endpoints for these reasons; other systems may not. I would point out the possibility and describe the use cases, but I wouldn't outright *recommend* one approach over another.

**Comment by whitehatguy** [comment]
Sounds good, I'll update as such.

**Comment by bakerdb** [comment]
Great idea!  

Also has relevance to the question regarding when should clients be required to present credentials  (#79), as the policy might be based on which URL the client comes in through.
