### ISSUE TITLE
Can an EHR's "issuer" and "subject" values change over time?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#78]
>   Exactly what happens in a scenario where a website needs to change its issuer value?  Perhaps an  organization is re-named.  What about the permanency of identifiers?  Should an opaque identifier be used for individuals, in the event that other identifying information changes in the underlying implementation?  Should this be in a format to support web-finger to allow future authentication-only?  Since advertising the location of the authorization and token endpoints are required in the OpenID Provider Configuration document, should implementations make best effort to make those the same as the authorization endpoints for SMART/FHIR?  What happens if a  non-passive    change occurs that breaks compatibility?

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-78

**Comment by jmandel** [comment]
@whitehatguy when you say "where a website needs to change its issuer", do you mean when an EHR needs to change its issuer? I take this as an identity management problem that we shouldn't try to solve in-band with this specification.

When it comes to `subject` values, I think we should indeed recommend against incorporating any identifying information in these values.

**Comment by whitehatguy** [comment]
I was primarily concerned around what guarantees (if any) a solution is provided for the OpenID Connect assertion.  If the information is purely for aesthetics / context (display of the authenticated user's name) and/or for creating human-readable audit trails, then this was a non-concern.  

If a client application wants an identifier it can use for making its own authorization decisions (e.g. access to cached data, personal preferences, other PHI content not stored in the EHR), then what should it use?  OpenID Connect indicates that subjects are a ["[l]ocally unique and never reassigned identifier within the Issuer"][1].  As such, it is the combination of the issuer and subject that uniquely identifies users in a global namespace.  It's pretty much a given that at some point an organization will want to change the URL of their issuer value (perhaps they switch implementations, perhaps their organization changes names, etc.).  Is the only guidance that we can offer is that apps should be aware this might occur, and should consider it if protecting resources in such a manner?

[1]: http://openid.net/specs/openid-connect-core-1_0.html#Terminology

**Comment by jmandel** [comment]
So yes, in short we do want apps to use OpenID as a single-sign-on
solution, which can potentially be used for app-internal authorization
decisions as you've described. This is obviously a deep problem (and
borders on philosophy when you get into edge cases); beyond the core OIDC
language that you've quoted, I'm not sure what more we can/should say.
Happy to have suggestions here, but my current take is just the guidance
you've proposed (ensure apps are aware of the issues).

**Comment by whitehatguy** [comment]
So is it agreed there is a reasonable expectation that client applications should allow the authorization server to change the value of its issuer (and/or one or more principals)? If so, it should be called out (also indicating that the means of how such changes are communicated are outside the scope of the actual technical specification.)

**Comment by bakerdb** [comment]
This is a great question.  In most cases, clients are likely to use local user IDs for their own decision-making, since users tend to have multiple IDs across settings and apps.  But if the client is relying on an OID provider to authenticate the identity associated with that ID, it needs to be able to trust the issuer (which would seem to require that the issuer be unrecognizable).  Most likely the issuer will have changed its cert as well, so the TLS authentication will not be helpful.  In the Argonaut use cases, all clients are pre-approved and registered.  Perhaps we should state as "best practice" the need for OID providers to inform clients of any changes in their issuer IDs?
