### ISSUE TITLE
What http "schemes" may a redirect_uri use?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#80]
>   Are these restricted to purely web schemes, or are native application redirects allowed?  That particular detail imparts some requirements on an authorization server.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-80

**Comment by kpshek** [comment]
What are some examples of the additional requirements a custom redirect scheme will impart on the authorization server, @whitehatguy?

Is it things outlined in this [OAuth 2.0 for Native Apps draft specification](http://tools.ietf.org/id/draft-wdenniss-oauth-native-apps-00.html#namespace-considerations)?

**Comment by whitehatguy** [comment]
When a native re-direct occurs from a web application to a native application, you're generally left with a browser window/tab.  Additionally, there's no guarantee in many cases that the scheme handler is registered on the target device -- in these situations, the authorization server would need to have a page that describes to the user what is happening, and the remediation steps if the native application fails to load (e.g. check that it is installed, maybe even provide a link to the appropriate app store(s)).

If all redirect URIs are required to be https:// schemes, this puts the burden on the client app developer to provide their own resource that performs this action.  This may or may not be desirable -- there aren't any guarantees that the app developer will or won't provide a proper experience, and the experience definitely won't be uniform between these types of native applications.

**Comment by jmandel** [comment]
Our intention is to allow `https` redirect URLs as well as custom schemes that work on native devices. I think custom schemes are important because they enable an app architecture that runs entirely on-device with no web-based component involved at runtime.

Agreed that the Authorization Server can and should help to orient the user at launch time.

**Comment by whitehatguy** [comment]
@kpshek  The [native app spec][1] discusses at a high level how such integration works and makes recommendations, but doesn't prescribe usability considerations.  I did find it interesting they prescribe 
[PKCE][2] for such public clients -- I'm going to read that draft and see what kind of use cases it might apply to, and if they overlap ours.

[1]: https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-00
[2]: https://tools.ietf.org/html/draft-ietf-oauth-spop

**Comment by jmandel** [comment]
My understanding (please correct my if I'm wrong) is that PKCE is designed
to mitigate a threat where a malicious app has been installed alongside a
legitimate app on a mobile device. We need to decide where this fits in our
threat model. (Up this point, I've believed that if we have malicious apps
running on the end-user's device, we've got bigger problems -- but perhaps
this is too narrow-minded.)

**Comment by whitehatguy** [comment]
I read the spec - it seems useful for the specific attack prescribed.  Half of it would have not been required if they had simply made the "state" parameter in the original OAuth2 spec functionally equivalent to the "plain" mechanism.

Assuming that the majority of access is via "launch" from within the health record, this doesn't provide much in the way of threat protection.  If the user is going the other direction (starting in native app), the attacker would have to know (or somehow eavesdrop) the specific FHIR service the app was attempting to use (or perhaps, try knocking on everyone's door with the authorization code...).  It's a passive addition;  a client and authorization server could utilize it where available without harming other participants.  It might be worth making it a recommended (but not required) feature.

**Comment by jmandel** [comment]
From the client perspective, trying to participate in PKCE when the server doesn't support it is no big deal: you wind up passing a couple of extra parameters (to the authorize and the token endpoints) that get ignored. But from a server perspective, if a server requires PKCE this will break with clients that don't support it. So I'm hesitant to call it "passive" in this regard unless we're very clear that servers should implement the [optional backwards compatibility](https://tools.ietf.org/html/draft-ietf-oauth-spop-15#section-5) described in PKCE.

My suggestion would be to point out that PKCE exists, and to suggest following the specification as it develops through the IETF draft process. I'm hesitant to outright recommend this for the draft.

**Comment by whitehatguy** [comment]
I missed the part where backwards compatibility was optional -- I'm definitely in agreement that servers need to operate with backwards compatibility mode. 

I'm in agreement with your last sentiment -- I'll add a blurb in the security considerations to this effect.

**Comment by bakerdb** [comment]
We have stated that client registration is outside the scope of our specification.  Our use cases simply state that the client has been pre-approved by the institution and registered with the AS.  I suggest removing the Registration section from this specification.

**Comment by whitehatguy** [comment]
I'm in favor or removing this per Dixie's comment.  I do think we should indicate in the security considerations that EHRs should explicitly white list return_to URLs, and where provided, launch URLs.  Any objections?

**Comment by jmandel** [comment]
I agree with all of the considerations you've suggested we include. I would
also like to maintain our recommendation to use OAuth2 dynamic client
registration in cases where an automated api for registration is desired. I
don't see a downside and it helps point folks to a really useful building
block. Any concerns with this?

**Comment by whitehatguy** [comment]
My only concern from a specification perspective is how to word/offer such advice, given that we're removing the registration section.  We could provide specific use case scenarios where such types of registration should be considered (e.g. instances where individual installations of an application are provided their own client identifier) as part of the security considerations.

Outside of the specification itself, is there need for some other form of group or consortium for policy guidance to foster interoperability?  Dynamic client registration is, as you stated, more akin to "building blocks" -- two or more authorization server implementations could easily devise two incompatible approaches for addressing a single use case.


> I agree with all of the considerations you've suggested we include. I would also like to maintain our recommendation to use OAuth2 dynamic client registration in cases where an automated api for registration is desired. I don't see a downside and it helps point folks to a really useful building block. Any concerns with this?

**Comment by jmandel** [comment]
I don't think we should remove the section entirety; we should use it to
lift things that are universal truths and general recommendations.

**Comment by whitehatguy** [comment]
I'd propose then that this specification should:

- Mention that the registration mechanism is an extension point and is left undefined.
- Recommend that authors of protocol extensions for automated registration use DCR as a basis.
- Provide the use case of per-installation registration as an example use case for why an extension might be developed.

I'm hesitant to state that using DCR is a "general recommendation" as I think it would actually harm general interoperability without inclusion of a concretely-defined profile.

**Comment by bakerdb** [comment]
This sounds good to me.
