### ISSUE TITLE
JWT client auth instead of HTTP basic?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#81]
>   HEART is proceeding with the use of JWK URIs for keys for client authentication -- I'm pretty much in agreement with that approach; can we list that as a registration requirement for client apps that need authN?  

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-81

**Comment by jmandel** [comment]
I'm supportive of this change; it avoid relying on shared secrets for authentication, and aligns better with the [OIDC HEART workgroup](http://openid.net/wg/heart/)

**Comment by whitehatguy** [comment]
Should we get a poll from early implementers?

**Comment by jmandel** [comment]
Yes. Will probably be a better question after the next Argonaut sprint when
we ask participants to actually implement OAuth 2 for the first time. But
no harm raising the issue early!

**Comment by bakerdb** [comment]
I support this approach.  However, we have stated that client registration is outside the scope of this specification.  The only thing we've said about registration is the the client has been pre-approved by the institution and registered with the AS.
