### ISSUE TITLE
Communicating error conditions with error_uri

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#82]
>   I added the following as the question was repeatedly raised as to whose responsibility it was to react to and fix   problems that occur with security.  I'm interested in feedback on this proposal.  

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-82

**Comment by jmandel** [comment]
I agree with this analysis and support use of `error_uri` as described. To be clear, this means that, on certain kinds of errors, the authorization server redirects to an app's `redirect_uri` and provides a few fields of free-text and structured data explaining what happened. One of these fields is an `error_uri` where users can go to learn more about what went wrong.

Note that some errors (e.g. an app that's not registered) *shouldn't* be reported back this way, because we don't want to redirect to an app that's not registered with us.

**Comment by whitehatguy** [comment]
I'm considering posting on the Google Group to point people to this for additional feedback before closing this particular issue.  I probably do no need to clarify it is only returned in only those cases where it is allowed to return errors as specified in the OAuth 2.0 framework.

**Comment by jmandel** [comment]
Sounds like a good idea to me!

**Comment by bakerdb** [comment]
I support use of error_uri as described.
