### ISSUE TITLE
API for revoking credentials?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#83]
>   Should we have a global revocation mechanism for client credential keys?  I suggest a JWK endpoint, allowing clients to rotate keys, and more critically, allowing them to revoke keys.  Such documents could self-describe their caching requirements via standard HTTP semantics.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-83

**Comment by jmandel** [comment]
@whitehatguy I assume you've reviewed the OAuth dynamic client registration specification -- the [recommendation there](https://tools.ietf.org/html/rfc7591#section-2) is to have clients register a `jwks_uri` rather than a `jwks` directly -- which provides a reference to a key that can be rotated by the client at will. Thoughts about this approach?

(Note that an earlier version of dyn reg contained a complete maintenance API that clients could call to update fields, keys, etc; but this was stripped to gain broader support for a narrower spec, and broken out into a separate component that perhasp @jricher could point us to.)

**Comment by jricher** [comment]
The "maintenance API" is now RFC7592 https://tools.ietf.org/html/rfc7592

**Comment by whitehatguy** [comment]
@jmandel Correct - I was proposing the registration of a jwks_uri.  We've been up and running with a jwks_uri for one of our services now for several weeks that auto-rotates its own keys, and we've found it to be very elegant.

**Comment by jmandel** [comment]
Cool! And on  the relying side (i.e. in your AS) you just respect the http  cache times that the jwks resource returns to know when to re-fetch?

Of course this jwks_uri approach does break down if we ever want  to allow non-web apps (with no web server) to authenticate. For example, a native app that  registers separately for every individual device on which it runs...

**Comment by whitehatguy** [comment]
With respect to the cache times - you're spot on (using HTTP caching semantics -- expires, etag, etc.).

I see the native app registration as having a completely different threat model -- it would be justifiable if it used a different authentication model.  I'd love to have a round-table discussion on per-app registration -- I see different possible use cases for both patients and providers where it could provide value.

**Comment by jricher** [comment]
Native apps are one of the reasons that jwk-by-value was added to the spec. You can securely generate a keypair on the device and register it with the server.

**Comment by bakerdb** [comment]
We have stated that client registration is outside the scope of the Argonaut authorization API.  
The use case states as a pre-condition that clients have been "pre-approved" and registered.  How either of these is accomplished is outside our scope.

**Comment by whitehatguy** [comment]
Is app authentication something we feel we can standardize on with this specification (perhaps with one or more profiles of dynamic registration and/or other extensions), or is that going to be an area where we concede variability will need to exist to accommodate the various policy requirements that might exist in the wild?  Examples:

- Dynamic registration of individual installations of applications to allow providers control over allowed devices.
- Use of PKI-based authentication for government institutions (the U.S. Federal Direct Exchange working group expressed a definite desire for this) alongside other policy exchange mechanisms (perhaps used in conjunction with some form of dynamic registration)
- Dynamic registration of applications where a patient decides to utilize any app they choose (U.S.'s Meaningful Use 3, similar to the first example with the exception that it's a patient's choice), and is registered in such a way that other applications cannot impersonate one previously registered by the user.

**Comment by bakerdb** [comment]
This sounds to me like two separate questions:  1) whether we want to include dynamic registration as a requirement, and 2) whether we want to standardize on app authentication.  

Standardizing on dynamic registration sounds fine to me; I think that's what implementers will be doing anyway.  

I think variability will continue to exist w.r.t. client authentication, with government organizations always having more stringent requirements than the private sector is ready for.   However, we could specify a minimal threshold.

**Comment by jricher** [comment]
In HEART, we're leaning toward standardizing both of these.

1) Dynamic registration required to be implemented by authorization servers. This doesn't mean that all clients have to be dynamically registered or that all functionality be made available to dynamically registered clients, but its availability as a baseline function is going to be very important.

2) Authentication through asymmetric key signatures. We're requiring all clients to register keys (through a URI or by value) and any authentication to the token endpoint is done using this key. We're not allowing client secrets right now, though public clients are allowed in limited circumstances (like the implicit flow).

I agree that there will be variability in the field, which is why we're trying to mandate a minimum security bar for this use case.

**Comment by whitehatguy** [comment]
Okay, I'm going to float a proposal - honest feedback welcomed:

- Indicate that for client authentication, use of JWT tokens is required unless overridden by a separate profile (e.g. government (not necessarily U.S.) defined profiles).
- Define two options for exchanging keying material:
  - Public JWK URI (applicable to most client-server apps, such as web apps.)
  - Dynamic Registration (to support individual installations of native clients, define explicit profile w/ software statement similar to HEART)
    - Question: For provider-facing use cases, should we also define the "initial access token" mechanism to support a use case where an administrator needs explicit control over on-boarding installations?

This would provide explicit profiles that could be tested for conformance, would handle the three primary use cases that I'm familiar with (client/server apps, combating native phishing apps targeted at patients, allowing admin provisioning for native clients for provider use), and would declare that it's intended that it is extensible to allow policy groups to define their own standards (e.g. models similar to Direct Trust).

**Comment by jmandel** [comment]
I think this makes a lot of sense (recognizing, of course, that it makes a
breaking change to our current authorization protocol, which uses a shared
client_secret for authentication).

One question I have is: do we want to allow non-dynamically-registered apps
to supply a JWK directly, in addition to supplying them by JWKS URL? While
I agree that providing a URL is "better" for several reasons (including an
easier key rotation process), I don't know that it's worth outright
prohibiting the direct registration of a key.

Thoughts?

  Josh

**Comment by jricher** [comment]
I think it makes sense, too. I would be fine with both static and dynamic clients registering a JWK through either a URI or through a value. I think that you can control behavior by policy and audit, especially with the non-dynamic apps. Not every kind of app is going to be able to host a key URL, but those that can really should.

Brainstorm thought: It might be useful to standardize something in the software statement that says "this client MUST provide its JWK by value and it MUST be a unique key" to handle the cases where we know something is a native app, for instance, and it should be generating its own key onboard the device. I don't know off hand how to do that in the statement so it's something we'd have to come up with.

**Comment by jmandel** [comment]
I agree that a "jwk by value only" property in the software statement would be nice to have. 

As for the question of whether we should also support an initial access token for explicit as in control over provisioning: I would want to understand the use case a bit better (i.e. When, in the explicit provisioning process, area values locked down?) and tk think through whether the semantics of this process could fit within the software statement model (for example, ssuing a device-specific software statement for this use case).

**Comment by whitehatguy** [comment]
Here's a sample scenario for initial token use in a hospital environment:

Hospital I.T. purchases 5 mobile devices (let's say iPads) for use by physicians.  Their default stance is that B.Y.O.D. is disallowed as they had a previous incident of malware on one of the physician's devices, and now only wish to allow devices that have MDM (mobile device management) installed to control what software is allowed to be installed.  They want to install and use software from the traditional app store, but don't want just anyone to be able to bring in a device and use it in their environment.  For this, they'd prefer a process where they can "white-list" the device (or in this case, "white-list" the installation of client apps.)  

In this model, an administrator would type (or copy/paste, or QR-code scan) in a registration code (the "initial" access token), provided through a console application provided by the EHR.  As you mentioned, a device-specific software statement could also fulfill this use case - the question does arise on how the administrator would "install" such a software statement with the software (much easier with a PC, probably a pain on iOS).  

This isn't the only way a requirement of this nature could be met.  For example, the requirement could be shifted such that the authentication solution is required perform some form of "device verification" before allowing authorization to proceed.

**Comment by whitehatguy** [comment]
I just realized we might have spiraled off a bit into the weeds (although I think it is good discussion).  If we agree that those entities that aren't "per-instance" clients are using a json key url, then this particular question was satisfied.  Other "per-instance" clients' registrations would likely be revoked by either the user or by an administrator on behalf of users if particular client(s) were deemed compromised.

**Comment by jmandel** [comment]
I think we agree that non-"per-instance" clients *may* use a JSON web key
url. But we shouldn't prevent them from supplying a JSON web key directly,
in my view. That is: at the specification level, we should allow both and
simply comment on considerations about the advantages/disadvantages of each.

  -J

**Comment by whitehatguy** [comment]
You're correct in that we should allow for supplying a JSON web key directly - the use case there would be a native client/server application that has no web-facing counterpart.  We could document in the security considerations enumerated reasons for publishing it, but I'm in general agreement it should be allowed.

Did you have any other specific examples of disadvantages to publishing the JSON Web Key or advantages to supplying it directly?  The only ones I could think from an authorization server perspective is dealing with outbound firewall rules mandated by a data center operator.
