### ISSUE TITLE
Use of "default browser"

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#85]
Re 2.1.2:  "SMART applications that are written natively for a platform SHOULD utilize the operating system's default browser when performing the authorization request such that the authorization server may comply with any security controls that have been imparted upon it. Such controls may include:

Support for single sign-on.
Support for anti-phishing controls implemented via persistent browser state or browser plug-ins.
Support for external native applications for sign-on.
External regulatory requirements that would prohibit user credentials from being entered via an embedded browser within the SMART application.
Such "native" applications MAY support orchestrating the authorization flow in an embedded browser where requested out-of-band by the EHR provider."

An OS's "default browser" is not always (perhaps "rarely") the most secure configuration, nor even the configuration required by institutional policy.  Further, this kind of materials is more appropriately contained in implementation guidance, not in a core profile.  I suggest deleting all of the content above.

**Comment by jmandel** [comment]
I think the language can be cleaned up, but makes an important point, @bakerdb  -- namely, that it's inappropriate for apps to redirect to the authorization server via **in-app** browser widgets. This is a common practice that (to my mind) undermines the whole point of OAuth (namely: to avoid asking users to share their AS credentials with each app they want to use).

**Comment by whitehatguy** [comment]
@jmandel - Since you pointed out the [OAuth 2.0 for Native Apps Draft][1], I was considering updating the wording to point to the details/explanation in section 6.1 of that specification.  Does that seem reasonable?

[1]: https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-00

**Comment by jmandel** [comment]
I think it's a great document. One concern is that the draft says "Both the client and the Authorization Server MUST support PKCE [PKCE] to use custom URI schemes" -- whereas according to our analysis in #80 we intended to make a recommendation rather than impose a requirement.

**Comment by bakerdb** [comment]
@jmandel @whitehatguy - I think 6.1 in [OAuth 2.0 for Native Apps Draft] (https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-00) does a good job of explaining the risks.  I'm going to submit a PR to revise the wording and incorporate a reference to this section.

**Comment by jmandel** [comment]
Dixie has proposed language in #87 to address this; I'll apply it and close the issue. Feel free to re-open if anything looks amiss!
