### ISSUE TITLE
Read/Write scopes do not cover all scenarios.

### ISSUE THREAD

**Issue by izi** [smart-on-fhir/smart-on-fhir.github.io#97]
Currently the format for user/patient scope looks like:

```
patient/:resourceType.(read|write)
```

The issue is that 'read' effectively means reading data and 'write' means that you can create/updated/delete data. You can imagine situations where you allow user to read/update data but you don't want him to have delete patient data privilege.

Is it possible to extend it to cover at least delete as separate privilege?

```
patient/:resourceType.(read|write|delete)
```

**Comment by jmandel** [comment]
It's a great point, @izi ! We've only really begun to explore the write-related use cases, so we began with the smallest model that we thought could conceivably work. Actually, it might be more common to give an app the ability to create new resources, but not to updated/delete any resources (e.g. a blood pressure cuff might only be allowed to send new data). Happy to think through additions here, but we're hoping to inform these decisions with some real-world implementation experience. This will be increasingly important as we enter the MU3 era of patient-generated data collection.

**Comment by whitehatguy** [comment]
I think it should be pointed out that the scopes only represent the permissions to act on the user's behalf, as it's not really possible to represent all of the fine-grain details of what a user may (or may not) be allowed to do with FHIR scopes.  If the user doesn't have the ability to delete a record, neither would an application acting on the user's behalf.  Regardless - your point is still valid for other use cases, including future cases as Josh mentioned for resources that collect user-generated data.  While MU3 only dictates view, download, transmit requirements, I can imagine those use cases won't be too far behind.

**Comment by jmandel** [comment]
Just to clarify the point about patient-generated data: MU3 does require "Patient-generated health data or data from a non-clinical setting is incorporated into the certified EHR technology for more than 15% of all unique patients". 

Note that CMS does not require an *API* for this functionality, but the functionality is required.

And the right APIs will make this goal easier to achieve.
